// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: shinzonetwork/sourcehub/v1/query.proto

package sourcehubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_RequestStatus_FullMethodName              = "/shinzonetwork.sourcehub.v1.Query/RequestStatus"
	Query_PendingRequestsByRequestor_FullMethodName = "/shinzonetwork.sourcehub.v1.Query/PendingRequestsByRequestor"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	RequestStatus(ctx context.Context, in *QueryRequestStatusRequest, opts ...grpc.CallOption) (*QueryRequestStatusResponse, error)
	PendingRequestsByRequestor(ctx context.Context, in *QueryPendingRequestsByRequestorRequest, opts ...grpc.CallOption) (*QueryPendingRequestsByRequestorResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RequestStatus(ctx context.Context, in *QueryRequestStatusRequest, opts ...grpc.CallOption) (*QueryRequestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRequestStatusResponse)
	err := c.cc.Invoke(ctx, Query_RequestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingRequestsByRequestor(ctx context.Context, in *QueryPendingRequestsByRequestorRequest, opts ...grpc.CallOption) (*QueryPendingRequestsByRequestorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPendingRequestsByRequestorResponse)
	err := c.cc.Invoke(ctx, Query_PendingRequestsByRequestor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	RequestStatus(context.Context, *QueryRequestStatusRequest) (*QueryRequestStatusResponse, error)
	PendingRequestsByRequestor(context.Context, *QueryPendingRequestsByRequestorRequest) (*QueryPendingRequestsByRequestorResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) RequestStatus(context.Context, *QueryRequestStatusRequest) (*QueryRequestStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestStatus not implemented")
}
func (UnimplementedQueryServer) PendingRequestsByRequestor(context.Context, *QueryPendingRequestsByRequestorRequest) (*QueryPendingRequestsByRequestorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingRequestsByRequestor not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_RequestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RequestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_RequestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RequestStatus(ctx, req.(*QueryRequestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingRequestsByRequestor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingRequestsByRequestorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingRequestsByRequestor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingRequestsByRequestor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingRequestsByRequestor(ctx, req.(*QueryPendingRequestsByRequestorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shinzonetwork.sourcehub.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestStatus",
			Handler:    _Query_RequestStatus_Handler,
		},
		{
			MethodName: "PendingRequestsByRequestor",
			Handler:    _Query_PendingRequestsByRequestor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shinzonetwork/sourcehub/v1/query.proto",
}
