coverage:
  ignore:
    - "api/**"
    - "data/**"
    - "devnet/**"
    - "docs/**"
    - "example/**"
    - "manual/**"
    - "proto/**"
    - "scripts/**"
    - "testutil/**" 
    - "**/*.pb.go"
    - "**/*.pb.gw.go"
    - "**/*.pulsar.go" 
    - "**/*_test.go"