// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shinzonetwork/view/v1/view.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// View represents a registered view.
type View struct {
	Name     string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Creator  string        `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Address  string        `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Data     []byte        `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Height   uint64        `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Metadata *ViewMetadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *View) Reset()         { *m = View{} }
func (m *View) String() string { return proto.CompactTextString(m) }
func (*View) ProtoMessage()    {}
func (*View) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a20d09dd0408598, []int{0}
}
func (m *View) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *View) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_View.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *View) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View.Merge(m, src)
}
func (m *View) XXX_Size() int {
	return m.Size()
}
func (m *View) XXX_DiscardUnknown() {
	xxx_messageInfo_View.DiscardUnknown(m)
}

var xxx_messageInfo_View proto.InternalMessageInfo

func (m *View) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *View) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *View) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *View) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *View) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *View) GetMetadata() *ViewMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// ViewMetadata is derived from a stored viewbundle.
type ViewMetadata struct {
	Query      string             `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Sdl        string             `protobuf:"bytes,2,opt,name=sdl,proto3" json:"sdl,omitempty"`
	RootType   string             `protobuf:"bytes,3,opt,name=root_type,json=rootType,proto3" json:"root_type,omitempty"`
	Lenses     []ViewLensMetadata `protobuf:"bytes,4,rep,name=lenses,proto3" json:"lenses"`
	ParseError string             `protobuf:"bytes,5,opt,name=parse_error,json=parseError,proto3" json:"parse_error,omitempty"`
}

func (m *ViewMetadata) Reset()         { *m = ViewMetadata{} }
func (m *ViewMetadata) String() string { return proto.CompactTextString(m) }
func (*ViewMetadata) ProtoMessage()    {}
func (*ViewMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a20d09dd0408598, []int{1}
}
func (m *ViewMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ViewMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ViewMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ViewMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewMetadata.Merge(m, src)
}
func (m *ViewMetadata) XXX_Size() int {
	return m.Size()
}
func (m *ViewMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ViewMetadata proto.InternalMessageInfo

func (m *ViewMetadata) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ViewMetadata) GetSdl() string {
	if m != nil {
		return m.Sdl
	}
	return ""
}

func (m *ViewMetadata) GetRootType() string {
	if m != nil {
		return m.RootType
	}
	return ""
}

func (m *ViewMetadata) GetLenses() []ViewLensMetadata {
	if m != nil {
		return m.Lenses
	}
	return nil
}

func (m *ViewMetadata) GetParseError() string {
	if m != nil {
		return m.ParseError
	}
	return ""
}

// ViewLensMetadata contains derived metadata for one lens in a viewbundle.
type ViewLensMetadata struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Args string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Hash string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *ViewLensMetadata) Reset()         { *m = ViewLensMetadata{} }
func (m *ViewLensMetadata) String() string { return proto.CompactTextString(m) }
func (*ViewLensMetadata) ProtoMessage()    {}
func (*ViewLensMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a20d09dd0408598, []int{2}
}
func (m *ViewLensMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ViewLensMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ViewLensMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ViewLensMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewLensMetadata.Merge(m, src)
}
func (m *ViewLensMetadata) XXX_Size() int {
	return m.Size()
}
func (m *ViewLensMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewLensMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ViewLensMetadata proto.InternalMessageInfo

func (m *ViewLensMetadata) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ViewLensMetadata) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *ViewLensMetadata) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*View)(nil), "shinzonetwork.view.v1.View")
	proto.RegisterType((*ViewMetadata)(nil), "shinzonetwork.view.v1.ViewMetadata")
	proto.RegisterType((*ViewLensMetadata)(nil), "shinzonetwork.view.v1.ViewLensMetadata")
}

func init() { proto.RegisterFile("shinzonetwork/view/v1/view.proto", fileDescriptor_6a20d09dd0408598) }

var fileDescriptor_6a20d09dd0408598 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0xed, 0xd0, 0x52, 0x60, 0x40, 0x43, 0x26, 0x68, 0x1a, 0x4d, 0x4a, 0x83, 0x0b, 0xbb, 0x6a,
	0x03, 0x7e, 0x80, 0x09, 0x09, 0x0b, 0x89, 0x6e, 0x1a, 0xe3, 0xc2, 0x0d, 0x19, 0xe8, 0x4d, 0xdb,
	0x08, 0x9d, 0x3a, 0x33, 0x80, 0xf8, 0x15, 0xfe, 0x8f, 0x2b, 0x77, 0x2c, 0x59, 0xba, 0x32, 0x06,
	0x7e, 0xc4, 0xcc, 0x74, 0x30, 0x8f, 0x97, 0x97, 0xb7, 0xea, 0x39, 0xe7, 0x9e, 0xb9, 0x3d, 0xf7,
	0xe6, 0xe2, 0x40, 0xe4, 0x45, 0xf9, 0x9d, 0x95, 0x20, 0xf7, 0x8c, 0x7f, 0x89, 0x77, 0x05, 0xec,
	0xe3, 0xdd, 0x58, 0x7f, 0xa3, 0x8a, 0x33, 0xc9, 0xc8, 0xb3, 0x1b, 0x47, 0xa4, 0x2b, 0xbb, 0xf1,
	0x8b, 0x41, 0xc6, 0x32, 0xa6, 0x1d, 0xb1, 0x42, 0xb5, 0x79, 0xf4, 0x0b, 0x61, 0xe7, 0x53, 0x01,
	0x7b, 0x42, 0xb0, 0x53, 0xd2, 0x0d, 0x78, 0x28, 0x40, 0x61, 0x27, 0xd1, 0x98, 0x78, 0xb8, 0xb5,
	0xe2, 0x40, 0x25, 0xe3, 0x5e, 0x43, 0xcb, 0x57, 0xaa, 0x2a, 0x34, 0x4d, 0x39, 0x08, 0xe1, 0x39,
	0x75, 0xc5, 0x50, 0xd5, 0x27, 0xa5, 0x92, 0x7a, 0xcd, 0x00, 0x85, 0xbd, 0x44, 0x63, 0xf2, 0x1c,
	0xbb, 0x39, 0x14, 0x59, 0x2e, 0x3d, 0x37, 0x40, 0xa1, 0x93, 0x18, 0x46, 0xde, 0xe2, 0xf6, 0x06,
	0x24, 0xd5, 0xfe, 0x56, 0x80, 0xc2, 0xee, 0xe4, 0x55, 0xf4, 0x60, 0xf8, 0x48, 0x45, 0xfc, 0x60,
	0xac, 0xc9, 0xff, 0x47, 0x73, 0xa7, 0x6d, 0xf7, 0x9d, 0xd1, 0x4f, 0x84, 0x7b, 0x77, 0x0d, 0x64,
	0x80, 0x9b, 0x5f, 0xb7, 0xc0, 0x0f, 0x66, 0x98, 0x9a, 0x90, 0x3e, 0xb6, 0x45, 0xba, 0x36, 0x93,
	0x28, 0x48, 0x5e, 0xe2, 0x0e, 0x67, 0x4c, 0x2e, 0xe4, 0xa1, 0x02, 0xcf, 0xd6, 0x7a, 0x5b, 0x09,
	0x1f, 0x0f, 0x15, 0x90, 0x19, 0x76, 0xd7, 0x50, 0x0a, 0x50, 0x13, 0xda, 0x61, 0x77, 0xf2, 0xfa,
	0x91, 0x68, 0xef, 0xa1, 0x14, 0xd7, 0xbf, 0x4f, 0x9d, 0xe3, 0x9f, 0xa1, 0x95, 0x98, 0xc7, 0x64,
	0x88, 0xbb, 0x15, 0xe5, 0x02, 0x16, 0xc0, 0x39, 0xe3, 0x7a, 0x2d, 0x9d, 0x04, 0x6b, 0x69, 0xa6,
	0x94, 0xd1, 0x1c, 0xf7, 0xef, 0xb7, 0x20, 0x4f, 0x71, 0xa3, 0x48, 0x75, 0xfa, 0x27, 0x49, 0xa3,
	0x48, 0xd5, 0x52, 0x29, 0xcf, 0x84, 0xc9, 0xae, 0xb1, 0xd2, 0x72, 0x2a, 0x72, 0x93, 0x5b, 0xe3,
	0xe9, 0xbb, 0xe3, 0xd9, 0x47, 0xa7, 0xb3, 0x8f, 0xfe, 0x9e, 0x7d, 0xf4, 0xe3, 0xe2, 0x5b, 0xa7,
	0x8b, 0x6f, 0xfd, 0xbe, 0xf8, 0xd6, 0xe7, 0x38, 0x2b, 0x64, 0xbe, 0x5d, 0x46, 0x2b, 0xb6, 0x89,
	0x6f, 0x2f, 0xa8, 0x66, 0xf9, 0x76, 0x19, 0x7f, 0xab, 0xaf, 0x49, 0x6d, 0x43, 0x2c, 0x5d, 0x7d,
	0x1f, 0x6f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x24, 0x1e, 0x69, 0xf9, 0x70, 0x02, 0x00, 0x00,
}

func (m *View) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *View) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *View) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintView(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Height != 0 {
		i = encodeVarintView(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintView(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintView(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintView(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintView(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ViewMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ViewMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ViewMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ParseError) > 0 {
		i -= len(m.ParseError)
		copy(dAtA[i:], m.ParseError)
		i = encodeVarintView(dAtA, i, uint64(len(m.ParseError)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Lenses) > 0 {
		for iNdEx := len(m.Lenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintView(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RootType) > 0 {
		i -= len(m.RootType)
		copy(dAtA[i:], m.RootType)
		i = encodeVarintView(dAtA, i, uint64(len(m.RootType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sdl) > 0 {
		i -= len(m.Sdl)
		copy(dAtA[i:], m.Sdl)
		i = encodeVarintView(dAtA, i, uint64(len(m.Sdl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Query) > 0 {
		i -= len(m.Query)
		copy(dAtA[i:], m.Query)
		i = encodeVarintView(dAtA, i, uint64(len(m.Query)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ViewLensMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ViewLensMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ViewLensMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintView(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Args) > 0 {
		i -= len(m.Args)
		copy(dAtA[i:], m.Args)
		i = encodeVarintView(dAtA, i, uint64(len(m.Args)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintView(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintView(dAtA []byte, offset int, v uint64) int {
	offset -= sovView(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *View) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovView(uint64(m.Height))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovView(uint64(l))
	}
	return n
}

func (m *ViewMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	l = len(m.Sdl)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	l = len(m.RootType)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	if len(m.Lenses) > 0 {
		for _, e := range m.Lenses {
			l = e.Size()
			n += 1 + l + sovView(uint64(l))
		}
	}
	l = len(m.ParseError)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	return n
}

func (m *ViewLensMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovView(uint64(m.Id))
	}
	l = len(m.Args)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovView(uint64(l))
	}
	return n
}

func sovView(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozView(x uint64) (n int) {
	return sovView(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *View) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowView
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: View: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: View: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &ViewMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipView(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthView
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ViewMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowView
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ViewMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ViewMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sdl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sdl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lenses = append(m.Lenses, ViewLensMetadata{})
			if err := m.Lenses[len(m.Lenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParseError", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParseError = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipView(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthView
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ViewLensMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowView
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ViewLensMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ViewLensMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowView
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthView
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthView
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipView(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthView
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipView(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowView
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowView
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowView
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthView
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupView
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthView
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthView        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowView          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupView = fmt.Errorf("proto: unexpected end of group")
)
