// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shinzonetwork/pool/v1/pool.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Pool holds the static metadata for a pool.
// Dynamic state (hosts, demands) lives in separate KV entries keyed by
// their respective sub-prefixes. The price is a network-wide value read
// from module state, not stored per pool.
type Pool struct {
	PoolAddress string     `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	ViewAddress string     `protobuf:"bytes,2,opt,name=view_address,json=viewAddress,proto3" json:"view_address,omitempty"`
	Config      PoolConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config"`
	CreatedAt   int64      `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *Pool) GetViewAddress() string {
	if m != nil {
		return m.ViewAddress
	}
	return ""
}

func (m *Pool) GetConfig() PoolConfig {
	if m != nil {
		return m.Config
	}
	return PoolConfig{}
}

func (m *Pool) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// PoolDetail is a denormalized view of a pool: metadata plus every host and
// demand currently in it. Useful for "show me this pool" queries and for
// downstream modules (settlement, querybalance) that need everything in
// one read.
type PoolDetail struct {
	Pool    Pool              `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool"`
	Hosts   []PoolHostEntry   `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts"`
	Demands []PoolDemandEntry `protobuf:"bytes,3,rep,name=demands,proto3" json:"demands"`
	Stats   PoolStats         `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats"`
	// is_active is true when the pool has at least MinHostsForActive hosts and is
	// therefore eligible to serve traffic. Derived from len(hosts), not stored.
	IsActive bool `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (m *PoolDetail) Reset()         { *m = PoolDetail{} }
func (m *PoolDetail) String() string { return proto.CompactTextString(m) }
func (*PoolDetail) ProtoMessage()    {}
func (*PoolDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{1}
}
func (m *PoolDetail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolDetail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDetail.Merge(m, src)
}
func (m *PoolDetail) XXX_Size() int {
	return m.Size()
}
func (m *PoolDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDetail proto.InternalMessageInfo

func (m *PoolDetail) GetPool() Pool {
	if m != nil {
		return m.Pool
	}
	return Pool{}
}

func (m *PoolDetail) GetHosts() []PoolHostEntry {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *PoolDetail) GetDemands() []PoolDemandEntry {
	if m != nil {
		return m.Demands
	}
	return nil
}

func (m *PoolDetail) GetStats() PoolStats {
	if m != nil {
		return m.Stats
	}
	return PoolStats{}
}

func (m *PoolDetail) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

// PoolStats accumulates operational telemetry for a pool — the per-query
// price set by the accounting service, the most recently reported
// utilization (0-100), and lifetime totals for queries served and rewards
// earned. Updated whenever a MsgAccountSettle includes the pool in its
// pools[] slice. Utilization and price are last-writer-wins; total_queries
// and total_rewards are monotonic sums.
type PoolStats struct {
	PoolAddress      string `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	Price            string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Utilization      uint64 `protobuf:"varint,3,opt,name=utilization,proto3" json:"utilization,omitempty"`
	TotalQueries     uint64 `protobuf:"varint,4,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	TotalRewards     string `protobuf:"bytes,5,opt,name=total_rewards,json=totalRewards,proto3" json:"total_rewards,omitempty"`
	LastUpdatedEpoch uint64 `protobuf:"varint,6,opt,name=last_updated_epoch,json=lastUpdatedEpoch,proto3" json:"last_updated_epoch,omitempty"`
}

func (m *PoolStats) Reset()         { *m = PoolStats{} }
func (m *PoolStats) String() string { return proto.CompactTextString(m) }
func (*PoolStats) ProtoMessage()    {}
func (*PoolStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{2}
}
func (m *PoolStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolStats.Merge(m, src)
}
func (m *PoolStats) XXX_Size() int {
	return m.Size()
}
func (m *PoolStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolStats.DiscardUnknown(m)
}

var xxx_messageInfo_PoolStats proto.InternalMessageInfo

func (m *PoolStats) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *PoolStats) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PoolStats) GetUtilization() uint64 {
	if m != nil {
		return m.Utilization
	}
	return 0
}

func (m *PoolStats) GetTotalQueries() uint64 {
	if m != nil {
		return m.TotalQueries
	}
	return 0
}

func (m *PoolStats) GetTotalRewards() string {
	if m != nil {
		return m.TotalRewards
	}
	return ""
}

func (m *PoolStats) GetLastUpdatedEpoch() uint64 {
	if m != nil {
		return m.LastUpdatedEpoch
	}
	return 0
}

// PoolConfig is the configuration that uniquely identifies a pool for a given view.
// Adding a new field changes the CREATE2 salt and produces a different pool address.
type PoolConfig struct {
	WindowSize uint64 `protobuf:"varint,1,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
}

func (m *PoolConfig) Reset()         { *m = PoolConfig{} }
func (m *PoolConfig) String() string { return proto.CompactTextString(m) }
func (*PoolConfig) ProtoMessage()    {}
func (*PoolConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{3}
}
func (m *PoolConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolConfig.Merge(m, src)
}
func (m *PoolConfig) XXX_Size() int {
	return m.Size()
}
func (m *PoolConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PoolConfig proto.InternalMessageInfo

func (m *PoolConfig) GetWindowSize() uint64 {
	if m != nil {
		return m.WindowSize
	}
	return 0
}

// PoolHost represents a host's membership in a pool.
type PoolHost struct {
	JoinedAt int64 `protobuf:"varint,1,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
}

func (m *PoolHost) Reset()         { *m = PoolHost{} }
func (m *PoolHost) String() string { return proto.CompactTextString(m) }
func (*PoolHost) ProtoMessage()    {}
func (*PoolHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{4}
}
func (m *PoolHost) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolHost.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolHost.Merge(m, src)
}
func (m *PoolHost) XXX_Size() int {
	return m.Size()
}
func (m *PoolHost) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolHost.DiscardUnknown(m)
}

var xxx_messageInfo_PoolHost proto.InternalMessageInfo

func (m *PoolHost) GetJoinedAt() int64 {
	if m != nil {
		return m.JoinedAt
	}
	return 0
}

// PoolDemand represents a single developer's demand registration on a pool.
type PoolDemand struct {
	// sdk.Int as base-10 string.
	Bond string `protobuf:"bytes,1,opt,name=bond,proto3" json:"bond,omitempty"`
	// sdk.Int as base-10 string. "0" or empty means no preference.
	PricePref string `protobuf:"bytes,2,opt,name=price_pref,json=pricePref,proto3" json:"price_pref,omitempty"`
	Binding   bool   `protobuf:"varint,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ExpiresAt int64  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *PoolDemand) Reset()         { *m = PoolDemand{} }
func (m *PoolDemand) String() string { return proto.CompactTextString(m) }
func (*PoolDemand) ProtoMessage()    {}
func (*PoolDemand) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{5}
}
func (m *PoolDemand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolDemand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolDemand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolDemand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDemand.Merge(m, src)
}
func (m *PoolDemand) XXX_Size() int {
	return m.Size()
}
func (m *PoolDemand) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDemand.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDemand proto.InternalMessageInfo

func (m *PoolDemand) GetBond() string {
	if m != nil {
		return m.Bond
	}
	return ""
}

func (m *PoolDemand) GetPricePref() string {
	if m != nil {
		return m.PricePref
	}
	return ""
}

func (m *PoolDemand) GetBinding() bool {
	if m != nil {
		return m.Binding
	}
	return false
}

func (m *PoolDemand) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

// PoolHostEntry wraps a PoolHost with both keys (pool + host addresses)
// so genesis import/query responses can reconstruct the full kv key path.
type PoolHostEntry struct {
	PoolAddress string   `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	HostAddress string   `protobuf:"bytes,2,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	Host        PoolHost `protobuf:"bytes,3,opt,name=host,proto3" json:"host"`
}

func (m *PoolHostEntry) Reset()         { *m = PoolHostEntry{} }
func (m *PoolHostEntry) String() string { return proto.CompactTextString(m) }
func (*PoolHostEntry) ProtoMessage()    {}
func (*PoolHostEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{6}
}
func (m *PoolHostEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolHostEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolHostEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolHostEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolHostEntry.Merge(m, src)
}
func (m *PoolHostEntry) XXX_Size() int {
	return m.Size()
}
func (m *PoolHostEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolHostEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PoolHostEntry proto.InternalMessageInfo

func (m *PoolHostEntry) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *PoolHostEntry) GetHostAddress() string {
	if m != nil {
		return m.HostAddress
	}
	return ""
}

func (m *PoolHostEntry) GetHost() PoolHost {
	if m != nil {
		return m.Host
	}
	return PoolHost{}
}

type PoolDemandEntry struct {
	PoolAddress       string     `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	RegistrantAddress string     `protobuf:"bytes,2,opt,name=registrant_address,json=registrantAddress,proto3" json:"registrant_address,omitempty"`
	Demand            PoolDemand `protobuf:"bytes,3,opt,name=demand,proto3" json:"demand"`
}

func (m *PoolDemandEntry) Reset()         { *m = PoolDemandEntry{} }
func (m *PoolDemandEntry) String() string { return proto.CompactTextString(m) }
func (*PoolDemandEntry) ProtoMessage()    {}
func (*PoolDemandEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0e539e5e4fb3e8, []int{7}
}
func (m *PoolDemandEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolDemandEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolDemandEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolDemandEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDemandEntry.Merge(m, src)
}
func (m *PoolDemandEntry) XXX_Size() int {
	return m.Size()
}
func (m *PoolDemandEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDemandEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDemandEntry proto.InternalMessageInfo

func (m *PoolDemandEntry) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *PoolDemandEntry) GetRegistrantAddress() string {
	if m != nil {
		return m.RegistrantAddress
	}
	return ""
}

func (m *PoolDemandEntry) GetDemand() PoolDemand {
	if m != nil {
		return m.Demand
	}
	return PoolDemand{}
}

func init() {
	proto.RegisterType((*Pool)(nil), "shinzonetwork.pool.v1.Pool")
	proto.RegisterType((*PoolDetail)(nil), "shinzonetwork.pool.v1.PoolDetail")
	proto.RegisterType((*PoolStats)(nil), "shinzonetwork.pool.v1.PoolStats")
	proto.RegisterType((*PoolConfig)(nil), "shinzonetwork.pool.v1.PoolConfig")
	proto.RegisterType((*PoolHost)(nil), "shinzonetwork.pool.v1.PoolHost")
	proto.RegisterType((*PoolDemand)(nil), "shinzonetwork.pool.v1.PoolDemand")
	proto.RegisterType((*PoolHostEntry)(nil), "shinzonetwork.pool.v1.PoolHostEntry")
	proto.RegisterType((*PoolDemandEntry)(nil), "shinzonetwork.pool.v1.PoolDemandEntry")
}

func init() { proto.RegisterFile("shinzonetwork/pool/v1/pool.proto", fileDescriptor_4e0e539e5e4fb3e8) }

var fileDescriptor_4e0e539e5e4fb3e8 = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0x13, 0x3d,
	0x10, 0x8e, 0x9b, 0x4d, 0x9b, 0xcc, 0xb6, 0xfa, 0x7f, 0xac, 0x22, 0xad, 0xa8, 0x48, 0xb7, 0x0b,
	0x82, 0x1c, 0x68, 0xa2, 0x06, 0x71, 0x40, 0x42, 0x82, 0x94, 0x16, 0xc1, 0xad, 0x6c, 0xc5, 0x85,
	0xcb, 0x6a, 0x93, 0x75, 0x13, 0xc3, 0xd6, 0x5e, 0x6c, 0x27, 0x69, 0xf3, 0x14, 0x7d, 0x08, 0x0e,
	0x1c, 0x78, 0x90, 0x1e, 0x7b, 0xe4, 0x54, 0xa1, 0xf6, 0x45, 0x90, 0xed, 0xdd, 0x36, 0x8d, 0x50,
	0xc8, 0x69, 0xd7, 0x9f, 0xbf, 0x6f, 0x3c, 0xf6, 0x7c, 0x33, 0xe0, 0xcb, 0x01, 0x65, 0x13, 0xce,
	0x88, 0x1a, 0x73, 0xf1, 0xb5, 0x95, 0x71, 0x9e, 0xb6, 0x46, 0x3b, 0xe6, 0xdb, 0xcc, 0x04, 0x57,
	0x1c, 0xdf, 0xbf, 0xc3, 0x68, 0x9a, 0x9d, 0xd1, 0xce, 0x83, 0xf5, 0x3e, 0xef, 0x73, 0xc3, 0x68,
	0xe9, 0x3f, 0x4b, 0x0e, 0x7e, 0x22, 0x70, 0x0e, 0x38, 0x4f, 0xf1, 0x16, 0xac, 0x6a, 0x66, 0x14,
	0x27, 0x89, 0x20, 0x52, 0x7a, 0xc8, 0x47, 0x8d, 0x5a, 0xe8, 0x6a, 0xac, 0x63, 0x21, 0x4d, 0x19,
	0x51, 0x32, 0xbe, 0xa1, 0x2c, 0x59, 0x8a, 0xc6, 0x0a, 0xca, 0x6b, 0x58, 0xee, 0x71, 0x76, 0x44,
	0xfb, 0x5e, 0xd9, 0x47, 0x0d, 0xb7, 0xbd, 0xd5, 0xfc, 0x6b, 0x32, 0x4d, 0x7d, 0xe4, 0x5b, 0x43,
	0xdc, 0x75, 0xce, 0x2f, 0x37, 0x4b, 0x61, 0x2e, 0xc3, 0x0f, 0x01, 0x7a, 0x82, 0xc4, 0x8a, 0x24,
	0x51, 0xac, 0x3c, 0xc7, 0x47, 0x8d, 0x72, 0x58, 0xcb, 0x91, 0x8e, 0x0a, 0x7e, 0x2c, 0x01, 0x68,
	0xed, 0x1e, 0x51, 0x31, 0x4d, 0xf1, 0x0b, 0x70, 0x74, 0x44, 0x93, 0xac, 0xdb, 0xde, 0x98, 0x73,
	0x58, 0x7e, 0x8c, 0xa1, 0xe3, 0x37, 0x50, 0x19, 0x70, 0xa9, 0xf4, 0x0d, 0xca, 0x0d, 0xb7, 0xfd,
	0x78, 0x8e, 0xee, 0x3d, 0x97, 0x6a, 0x9f, 0x29, 0x71, 0x9a, 0x07, 0xb0, 0x42, 0xfc, 0x0e, 0x56,
	0x12, 0x72, 0x1c, 0xb3, 0x44, 0x7a, 0x65, 0x13, 0xe3, 0xc9, 0x9c, 0x18, 0x7b, 0x86, 0x39, 0x1d,
	0xa5, 0x10, 0xe3, 0x57, 0x50, 0x91, 0x2a, 0x56, 0xd2, 0xdc, 0xd4, 0x6d, 0xfb, 0x73, 0xa2, 0x1c,
	0x6a, 0x5e, 0x91, 0x85, 0x11, 0xe1, 0x0d, 0xa8, 0x51, 0x19, 0xc5, 0x3d, 0x45, 0x47, 0xc4, 0xab,
	0xf8, 0xa8, 0x51, 0x0d, 0xab, 0x54, 0x76, 0xcc, 0x3a, 0xb8, 0x44, 0x50, 0xbb, 0xd1, 0x2d, 0x52,
	0xde, 0x75, 0xa8, 0x64, 0x82, 0xf6, 0x48, 0x5e, 0x57, 0xbb, 0xc0, 0x3e, 0xb8, 0x43, 0x45, 0x53,
	0x3a, 0x89, 0x15, 0xe5, 0xcc, 0x94, 0xd5, 0x09, 0xa7, 0x21, 0xfc, 0x08, 0xd6, 0x14, 0x57, 0x71,
	0x1a, 0x7d, 0x1b, 0x12, 0x41, 0x89, 0xbd, 0x8b, 0x13, 0xae, 0x1a, 0xf0, 0xa3, 0xc5, 0x6e, 0x49,
	0x82, 0x8c, 0x63, 0x91, 0x48, 0x93, 0x6e, 0x2d, 0x27, 0x85, 0x16, 0xc3, 0xcf, 0x00, 0xa7, 0xb1,
	0x54, 0xd1, 0x30, 0x4b, 0x8c, 0x03, 0x48, 0xc6, 0x7b, 0x03, 0x6f, 0xd9, 0x84, 0xfb, 0x5f, 0xef,
	0x7c, 0xb2, 0x1b, 0xfb, 0x1a, 0x0f, 0xb6, 0xad, 0x15, 0xac, 0x8d, 0xf0, 0x26, 0xb8, 0x63, 0xca,
	0x12, 0x3e, 0x8e, 0x24, 0x9d, 0x10, 0x73, 0x3f, 0x27, 0x04, 0x0b, 0x1d, 0xd2, 0x09, 0x09, 0x9e,
	0x42, 0xb5, 0x28, 0xa8, 0x7e, 0xb8, 0x2f, 0x9c, 0x32, 0x6b, 0x32, 0x64, 0x4c, 0x56, 0xb5, 0x40,
	0x47, 0x05, 0x27, 0x85, 0xc5, 0x74, 0x89, 0x30, 0x06, 0xa7, 0xcb, 0x59, 0x92, 0x3f, 0x98, 0xf9,
	0xd7, 0x26, 0x35, 0x8f, 0x13, 0x65, 0x82, 0x1c, 0xe5, 0xcf, 0x55, 0x33, 0xc8, 0x81, 0x20, 0x47,
	0xd8, 0x83, 0x95, 0x2e, 0x65, 0x09, 0x65, 0xb6, 0x0b, 0xaa, 0x61, 0xb1, 0xd4, 0x42, 0x72, 0x92,
	0x51, 0x41, 0xe4, 0x94, 0xbb, 0x73, 0xa4, 0xa3, 0x82, 0x33, 0x04, 0x6b, 0x77, 0x4c, 0xb7, 0x60,
	0x57, 0x6a, 0x4f, 0xce, 0x76, 0xa5, 0xc6, 0x0a, 0xca, 0x4b, 0x70, 0xf4, 0x32, 0xef, 0xc9, 0xcd,
	0x7f, 0xd8, 0xbd, 0x68, 0x15, 0x2d, 0x09, 0xbe, 0x23, 0xf8, 0x6f, 0xc6, 0xc3, 0x8b, 0x24, 0xb5,
	0x0d, 0x58, 0x90, 0x3e, 0x95, 0x4a, 0xc4, 0x6c, 0x36, 0xb5, 0x7b, 0xb7, 0x3b, 0x53, 0x63, 0xc3,
	0x76, 0xc4, 0x02, 0x63, 0xc3, 0x66, 0x52, 0x8c, 0x0d, 0x2b, 0xdb, 0xfd, 0x70, 0x7e, 0x55, 0x47,
	0x17, 0x57, 0x75, 0xf4, 0xfb, 0xaa, 0x8e, 0xce, 0xae, 0xeb, 0xa5, 0x8b, 0xeb, 0x7a, 0xe9, 0xd7,
	0x75, 0xbd, 0xf4, 0xb9, 0xd5, 0xa7, 0x6a, 0x30, 0xec, 0x36, 0x7b, 0xfc, 0xb8, 0x75, 0x77, 0x74,
	0xda, 0xd5, 0x60, 0xd8, 0x6d, 0x9d, 0xd8, 0x31, 0xaa, 0x4e, 0x33, 0x22, 0xbb, 0xcb, 0x66, 0x30,
	0x3e, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x49, 0x2e, 0x66, 0x19, 0x69, 0x05, 0x00, 0x00,
}

func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ViewAddress) > 0 {
		i -= len(m.ViewAddress)
		copy(dAtA[i:], m.ViewAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.ViewAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolDetail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolDetail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Demands) > 0 {
		for iNdEx := len(m.Demands) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Demands[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Hosts) > 0 {
		for iNdEx := len(m.Hosts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Hosts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Pool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PoolStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdatedEpoch != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.LastUpdatedEpoch))
		i--
		dAtA[i] = 0x30
	}
	if len(m.TotalRewards) > 0 {
		i -= len(m.TotalRewards)
		copy(dAtA[i:], m.TotalRewards)
		i = encodeVarintPool(dAtA, i, uint64(len(m.TotalRewards)))
		i--
		dAtA[i] = 0x2a
	}
	if m.TotalQueries != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.TotalQueries))
		i--
		dAtA[i] = 0x20
	}
	if m.Utilization != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.Utilization))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WindowSize != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.WindowSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoolHost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolHost) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolHost) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.JoinedAt != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.JoinedAt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoolDemand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolDemand) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolDemand) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x20
	}
	if m.Binding {
		i--
		if m.Binding {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.PricePref) > 0 {
		i -= len(m.PricePref)
		copy(dAtA[i:], m.PricePref)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PricePref)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Bond) > 0 {
		i -= len(m.Bond)
		copy(dAtA[i:], m.Bond)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Bond)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolHostEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolHostEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolHostEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Host.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.HostAddress) > 0 {
		i -= len(m.HostAddress)
		copy(dAtA[i:], m.HostAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.HostAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolDemandEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolDemandEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolDemandEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Demand.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.RegistrantAddress) > 0 {
		i -= len(m.RegistrantAddress)
		copy(dAtA[i:], m.RegistrantAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.RegistrantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.ViewAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = m.Config.Size()
	n += 1 + l + sovPool(uint64(l))
	if m.CreatedAt != 0 {
		n += 1 + sovPool(uint64(m.CreatedAt))
	}
	return n
}

func (m *PoolDetail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Pool.Size()
	n += 1 + l + sovPool(uint64(l))
	if len(m.Hosts) > 0 {
		for _, e := range m.Hosts {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	if len(m.Demands) > 0 {
		for _, e := range m.Demands {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	l = m.Stats.Size()
	n += 1 + l + sovPool(uint64(l))
	if m.IsActive {
		n += 2
	}
	return n
}

func (m *PoolStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.Utilization != 0 {
		n += 1 + sovPool(uint64(m.Utilization))
	}
	if m.TotalQueries != 0 {
		n += 1 + sovPool(uint64(m.TotalQueries))
	}
	l = len(m.TotalRewards)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.LastUpdatedEpoch != 0 {
		n += 1 + sovPool(uint64(m.LastUpdatedEpoch))
	}
	return n
}

func (m *PoolConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WindowSize != 0 {
		n += 1 + sovPool(uint64(m.WindowSize))
	}
	return n
}

func (m *PoolHost) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.JoinedAt != 0 {
		n += 1 + sovPool(uint64(m.JoinedAt))
	}
	return n
}

func (m *PoolDemand) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Bond)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.PricePref)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.Binding {
		n += 2
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovPool(uint64(m.ExpiresAt))
	}
	return n
}

func (m *PoolHostEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.HostAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = m.Host.Size()
	n += 1 + l + sovPool(uint64(l))
	return n
}

func (m *PoolDemandEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.RegistrantAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = m.Demand.Size()
	n += 1 + l + sovPool(uint64(l))
	return n
}

func sovPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPool(x uint64) (n int) {
	return sovPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViewAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ViewAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolDetail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolDetail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolDetail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hosts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hosts = append(m.Hosts, PoolHostEntry{})
			if err := m.Hosts[len(m.Hosts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Demands", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Demands = append(m.Demands, PoolDemandEntry{})
			if err := m.Demands[len(m.Demands)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Utilization", wireType)
			}
			m.Utilization = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Utilization |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalQueries", wireType)
			}
			m.TotalQueries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalQueries |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalRewards = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedEpoch", wireType)
			}
			m.LastUpdatedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowSize", wireType)
			}
			m.WindowSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolHost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolHost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolHost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinedAt", wireType)
			}
			m.JoinedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JoinedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolDemand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolDemand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolDemand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bond = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePref", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PricePref = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Binding", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Binding = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolHostEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolHostEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolHostEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Host.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolDemandEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolDemandEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolDemandEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Demand", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Demand.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPool = fmt.Errorf("proto: unexpected end of group")
)
