// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shinzonetwork/indexer/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryIndexersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryIndexersRequest) Reset()         { *m = QueryIndexersRequest{} }
func (m *QueryIndexersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIndexersRequest) ProtoMessage()    {}
func (*QueryIndexersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0346e39b6c4902b4, []int{0}
}
func (m *QueryIndexersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIndexersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIndexersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIndexersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexersRequest.Merge(m, src)
}
func (m *QueryIndexersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIndexersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexersRequest proto.InternalMessageInfo

func (m *QueryIndexersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryIndexersResponse struct {
	Indexers   []Indexer           `protobuf:"bytes,1,rep,name=indexers,proto3" json:"indexers"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryIndexersResponse) Reset()         { *m = QueryIndexersResponse{} }
func (m *QueryIndexersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIndexersResponse) ProtoMessage()    {}
func (*QueryIndexersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0346e39b6c4902b4, []int{1}
}
func (m *QueryIndexersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIndexersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIndexersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIndexersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexersResponse.Merge(m, src)
}
func (m *QueryIndexersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIndexersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexersResponse proto.InternalMessageInfo

func (m *QueryIndexersResponse) GetIndexers() []Indexer {
	if m != nil {
		return m.Indexers
	}
	return nil
}

func (m *QueryIndexersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryIndexerRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryIndexerRequest) Reset()         { *m = QueryIndexerRequest{} }
func (m *QueryIndexerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIndexerRequest) ProtoMessage()    {}
func (*QueryIndexerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0346e39b6c4902b4, []int{2}
}
func (m *QueryIndexerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIndexerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIndexerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIndexerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexerRequest.Merge(m, src)
}
func (m *QueryIndexerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIndexerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexerRequest proto.InternalMessageInfo

func (m *QueryIndexerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryIndexerResponse struct {
	Indexer Indexer `protobuf:"bytes,1,opt,name=indexer,proto3" json:"indexer"`
}

func (m *QueryIndexerResponse) Reset()         { *m = QueryIndexerResponse{} }
func (m *QueryIndexerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIndexerResponse) ProtoMessage()    {}
func (*QueryIndexerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0346e39b6c4902b4, []int{3}
}
func (m *QueryIndexerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIndexerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIndexerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIndexerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexerResponse.Merge(m, src)
}
func (m *QueryIndexerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIndexerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexerResponse proto.InternalMessageInfo

func (m *QueryIndexerResponse) GetIndexer() Indexer {
	if m != nil {
		return m.Indexer
	}
	return Indexer{}
}

type QueryIndexerCountRequest struct {
}

func (m *QueryIndexerCountRequest) Reset()         { *m = QueryIndexerCountRequest{} }
func (m *QueryIndexerCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIndexerCountRequest) ProtoMessage()    {}
func (*QueryIndexerCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0346e39b6c4902b4, []int{4}
}
func (m *QueryIndexerCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIndexerCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIndexerCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIndexerCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexerCountRequest.Merge(m, src)
}
func (m *QueryIndexerCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIndexerCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexerCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexerCountRequest proto.InternalMessageInfo

type QueryIndexerCountResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryIndexerCountResponse) Reset()         { *m = QueryIndexerCountResponse{} }
func (m *QueryIndexerCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIndexerCountResponse) ProtoMessage()    {}
func (*QueryIndexerCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0346e39b6c4902b4, []int{5}
}
func (m *QueryIndexerCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIndexerCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIndexerCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIndexerCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIndexerCountResponse.Merge(m, src)
}
func (m *QueryIndexerCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIndexerCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIndexerCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIndexerCountResponse proto.InternalMessageInfo

func (m *QueryIndexerCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryIndexersRequest)(nil), "shinzonetwork.indexer.v1.QueryIndexersRequest")
	proto.RegisterType((*QueryIndexersResponse)(nil), "shinzonetwork.indexer.v1.QueryIndexersResponse")
	proto.RegisterType((*QueryIndexerRequest)(nil), "shinzonetwork.indexer.v1.QueryIndexerRequest")
	proto.RegisterType((*QueryIndexerResponse)(nil), "shinzonetwork.indexer.v1.QueryIndexerResponse")
	proto.RegisterType((*QueryIndexerCountRequest)(nil), "shinzonetwork.indexer.v1.QueryIndexerCountRequest")
	proto.RegisterType((*QueryIndexerCountResponse)(nil), "shinzonetwork.indexer.v1.QueryIndexerCountResponse")
}

func init() {
	proto.RegisterFile("shinzonetwork/indexer/v1/query.proto", fileDescriptor_0346e39b6c4902b4)
}

var fileDescriptor_0346e39b6c4902b4 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x3f, 0x6f, 0xd4, 0x30,
	0x18, 0xc6, 0xcf, 0xfd, 0xc3, 0x95, 0xb7, 0x4c, 0xe6, 0x90, 0x42, 0x84, 0x42, 0x89, 0xaa, 0xb6,
	0x54, 0x60, 0x2b, 0x29, 0x5f, 0x80, 0x56, 0x02, 0x21, 0x31, 0x40, 0x36, 0x18, 0x40, 0xc9, 0x9d,
	0x95, 0x8b, 0xa0, 0x76, 0x1a, 0x3b, 0x47, 0x0b, 0x62, 0xe1, 0x13, 0x20, 0x31, 0xb0, 0xb1, 0x21,
	0xf1, 0x51, 0x3a, 0x56, 0x62, 0x61, 0x42, 0xe8, 0x8e, 0x95, 0xef, 0x80, 0xce, 0x76, 0x8e, 0x5c,
	0xd5, 0x53, 0xc2, 0x16, 0xdb, 0xcf, 0xf3, 0xbe, 0x3f, 0x3f, 0xaf, 0x15, 0xd8, 0x94, 0xc3, 0x8c,
	0xbf, 0x15, 0x9c, 0xa9, 0x37, 0xa2, 0x78, 0x45, 0x33, 0x3e, 0x60, 0xc7, 0xac, 0xa0, 0xa3, 0x80,
	0x1e, 0x95, 0xac, 0x38, 0x21, 0x79, 0x21, 0x94, 0xc0, 0xce, 0x9c, 0x8a, 0x58, 0x15, 0x19, 0x05,
	0x6e, 0x2f, 0x15, 0xa9, 0xd0, 0x22, 0x3a, 0xfd, 0x32, 0x7a, 0xf7, 0x46, 0x2a, 0x44, 0xfa, 0x9a,
	0xd1, 0x38, 0xcf, 0x68, 0xcc, 0xb9, 0x50, 0xb1, 0xca, 0x04, 0x97, 0xf6, 0x74, 0xb7, 0x2f, 0xe4,
	0xa1, 0x90, 0x34, 0x89, 0x25, 0x33, 0x6d, 0xe8, 0x28, 0x48, 0x98, 0x8a, 0x03, 0x9a, 0xc7, 0x69,
	0xc6, 0xb5, 0xd8, 0x6a, 0xb7, 0x16, 0xf2, 0x55, 0x10, 0x5a, 0xe7, 0xbf, 0x80, 0xde, 0xd3, 0x69,
	0xa5, 0x47, 0x66, 0x57, 0x46, 0xec, 0xa8, 0x64, 0x52, 0xe1, 0x07, 0x00, 0xff, 0x6a, 0x3a, 0x68,
	0x03, 0xed, 0xac, 0x87, 0x5b, 0xc4, 0x00, 0x90, 0x29, 0x00, 0x31, 0xf7, 0xb4, 0x00, 0xe4, 0x49,
	0x9c, 0x32, 0xeb, 0x8d, 0x6a, 0x4e, 0xff, 0x2b, 0x82, 0x6b, 0xe7, 0x1a, 0xc8, 0x5c, 0x70, 0xc9,
	0xf0, 0x01, 0xac, 0x59, 0x14, 0xe9, 0xa0, 0x8d, 0xe5, 0x9d, 0xf5, 0xf0, 0x16, 0x59, 0x14, 0x17,
	0xb1, 0xee, 0xfd, 0x95, 0xd3, 0x9f, 0x37, 0x3b, 0xd1, 0xcc, 0x88, 0x1f, 0xce, 0x61, 0x2e, 0x69,
	0xcc, 0xed, 0x46, 0x4c, 0x43, 0x30, 0xc7, 0x49, 0xe1, 0x6a, 0x1d, 0xb3, 0x8a, 0xc1, 0x81, 0x6e,
	0x3c, 0x18, 0x14, 0x4c, 0x4a, 0x9d, 0xc1, 0xe5, 0xa8, 0x5a, 0xfa, 0xcf, 0xe6, 0x83, 0x9b, 0x5d,
	0xeb, 0x3e, 0x74, 0x2d, 0x9d, 0x4d, 0xad, 0xf5, 0xad, 0x2a, 0x9f, 0xef, 0x82, 0x53, 0x2f, 0x7d,
	0x20, 0x4a, 0xae, 0x2c, 0x90, 0x1f, 0xc0, 0xf5, 0x0b, 0xce, 0x6c, 0xef, 0x1e, 0xac, 0xf6, 0xa7,
	0x1b, 0xba, 0xf3, 0x4a, 0x64, 0x16, 0xe1, 0x9f, 0x65, 0x58, 0xd5, 0x1e, 0xfc, 0x19, 0xc1, 0x5a,
	0x35, 0x07, 0x4c, 0x16, 0x73, 0x5d, 0xf4, 0x22, 0x5c, 0xda, 0x5a, 0x6f, 0x68, 0xfc, 0xdd, 0x0f,
	0xdf, 0x7f, 0x7f, 0x5a, 0xda, 0xc4, 0x3e, 0x6d, 0x7a, 0x8b, 0x12, 0x7f, 0x41, 0xd0, 0xb5, 0x05,
	0xf0, 0xdd, 0x76, 0x8d, 0x2a, 0x2e, 0xd2, 0x56, 0x6e, 0xb1, 0xee, 0x69, 0x2c, 0x82, 0xef, 0x34,
	0x63, 0xd1, 0x77, 0x76, 0xda, 0xef, 0xf1, 0x37, 0x04, 0x57, 0xea, 0x99, 0xe3, 0xb0, 0x5d, 0xdb,
	0xfa, 0xf0, 0xdc, 0xbd, 0xff, 0xf2, 0x58, 0x5e, 0xaa, 0x79, 0x6f, 0xe3, 0xed, 0x46, 0xde, 0x97,
	0x7a, 0xde, 0xfb, 0x8f, 0x4f, 0xc7, 0x1e, 0x3a, 0x1b, 0x7b, 0xe8, 0xd7, 0xd8, 0x43, 0x1f, 0x27,
	0x5e, 0xe7, 0x6c, 0xe2, 0x75, 0x7e, 0x4c, 0xbc, 0xce, 0xf3, 0x30, 0xcd, 0xd4, 0xb0, 0x4c, 0x48,
	0x5f, 0x1c, 0x9e, 0x2b, 0x66, 0x56, 0xc3, 0x32, 0xa1, 0xc7, 0xb3, 0xc2, 0xea, 0x24, 0x67, 0x32,
	0xb9, 0xa4, 0xff, 0x13, 0x7b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x9c, 0x0d, 0xf9, 0xf1,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Indexers(ctx context.Context, in *QueryIndexersRequest, opts ...grpc.CallOption) (*QueryIndexersResponse, error)
	Indexer(ctx context.Context, in *QueryIndexerRequest, opts ...grpc.CallOption) (*QueryIndexerResponse, error)
	IndexerCount(ctx context.Context, in *QueryIndexerCountRequest, opts ...grpc.CallOption) (*QueryIndexerCountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Indexers(ctx context.Context, in *QueryIndexersRequest, opts ...grpc.CallOption) (*QueryIndexersResponse, error) {
	out := new(QueryIndexersResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.indexer.v1.Query/Indexers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Indexer(ctx context.Context, in *QueryIndexerRequest, opts ...grpc.CallOption) (*QueryIndexerResponse, error) {
	out := new(QueryIndexerResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.indexer.v1.Query/Indexer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IndexerCount(ctx context.Context, in *QueryIndexerCountRequest, opts ...grpc.CallOption) (*QueryIndexerCountResponse, error) {
	out := new(QueryIndexerCountResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.indexer.v1.Query/IndexerCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Indexers(context.Context, *QueryIndexersRequest) (*QueryIndexersResponse, error)
	Indexer(context.Context, *QueryIndexerRequest) (*QueryIndexerResponse, error)
	IndexerCount(context.Context, *QueryIndexerCountRequest) (*QueryIndexerCountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Indexers(ctx context.Context, req *QueryIndexersRequest) (*QueryIndexersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Indexers not implemented")
}
func (*UnimplementedQueryServer) Indexer(ctx context.Context, req *QueryIndexerRequest) (*QueryIndexerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Indexer not implemented")
}
func (*UnimplementedQueryServer) IndexerCount(ctx context.Context, req *QueryIndexerCountRequest) (*QueryIndexerCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexerCount not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Indexers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIndexersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Indexers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.indexer.v1.Query/Indexers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Indexers(ctx, req.(*QueryIndexersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Indexer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIndexerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Indexer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.indexer.v1.Query/Indexer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Indexer(ctx, req.(*QueryIndexerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IndexerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIndexerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IndexerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.indexer.v1.Query/IndexerCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IndexerCount(ctx, req.(*QueryIndexerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shinzonetwork.indexer.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Indexers",
			Handler:    _Query_Indexers_Handler,
		},
		{
			MethodName: "Indexer",
			Handler:    _Query_Indexer_Handler,
		},
		{
			MethodName: "IndexerCount",
			Handler:    _Query_IndexerCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shinzonetwork/indexer/v1/query.proto",
}

func (m *QueryIndexersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIndexersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIndexersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIndexersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIndexersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIndexersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Indexers) > 0 {
		for iNdEx := len(m.Indexers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Indexers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryIndexerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIndexerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIndexerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIndexerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIndexerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIndexerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Indexer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryIndexerCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIndexerCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIndexerCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIndexerCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIndexerCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIndexerCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryIndexersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIndexersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Indexers) > 0 {
		for _, e := range m.Indexers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIndexerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIndexerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Indexer.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryIndexerCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIndexerCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryIndexersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIndexersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIndexersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIndexersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIndexersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIndexersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indexers = append(m.Indexers, Indexer{})
			if err := m.Indexers[len(m.Indexers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIndexerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIndexerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIndexerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIndexerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIndexerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIndexerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Indexer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIndexerCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIndexerCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIndexerCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIndexerCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIndexerCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIndexerCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
