// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shinzonetwork/indexer/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgIndexerAssertion struct {
	Signer            string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	ConsensusPubKey   string `protobuf:"bytes,2,opt,name=consensus_pub_key,json=consensusPubKey,proto3" json:"consensus_pub_key,omitempty"`
	DelegateAddress   string `protobuf:"bytes,3,opt,name=delegate_address,json=delegateAddress,proto3" json:"delegate_address,omitempty"`
	SourceChain       string `protobuf:"bytes,4,opt,name=source_chain,json=sourceChain,proto3" json:"source_chain,omitempty"`
	SourceChainId     uint64 `protobuf:"varint,5,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	AssertionId       string `protobuf:"bytes,6,opt,name=assertion_id,json=assertionId,proto3" json:"assertion_id,omitempty"`
	DelegateDigest    []byte `protobuf:"bytes,7,opt,name=delegate_digest,json=delegateDigest,proto3" json:"delegate_digest,omitempty"`
	DelegateSignature []byte `protobuf:"bytes,8,opt,name=delegate_signature,json=delegateSignature,proto3" json:"delegate_signature,omitempty"`
}

func (m *MsgIndexerAssertion) Reset()         { *m = MsgIndexerAssertion{} }
func (m *MsgIndexerAssertion) String() string { return proto.CompactTextString(m) }
func (*MsgIndexerAssertion) ProtoMessage()    {}
func (*MsgIndexerAssertion) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c48cfcae3522555, []int{0}
}
func (m *MsgIndexerAssertion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIndexerAssertion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIndexerAssertion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIndexerAssertion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIndexerAssertion.Merge(m, src)
}
func (m *MsgIndexerAssertion) XXX_Size() int {
	return m.Size()
}
func (m *MsgIndexerAssertion) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIndexerAssertion.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIndexerAssertion proto.InternalMessageInfo

func (m *MsgIndexerAssertion) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgIndexerAssertion) GetConsensusPubKey() string {
	if m != nil {
		return m.ConsensusPubKey
	}
	return ""
}

func (m *MsgIndexerAssertion) GetDelegateAddress() string {
	if m != nil {
		return m.DelegateAddress
	}
	return ""
}

func (m *MsgIndexerAssertion) GetSourceChain() string {
	if m != nil {
		return m.SourceChain
	}
	return ""
}

func (m *MsgIndexerAssertion) GetSourceChainId() uint64 {
	if m != nil {
		return m.SourceChainId
	}
	return 0
}

func (m *MsgIndexerAssertion) GetAssertionId() string {
	if m != nil {
		return m.AssertionId
	}
	return ""
}

func (m *MsgIndexerAssertion) GetDelegateDigest() []byte {
	if m != nil {
		return m.DelegateDigest
	}
	return nil
}

func (m *MsgIndexerAssertion) GetDelegateSignature() []byte {
	if m != nil {
		return m.DelegateSignature
	}
	return nil
}

type MsgIndexerAssertionResponse struct {
}

func (m *MsgIndexerAssertionResponse) Reset()         { *m = MsgIndexerAssertionResponse{} }
func (m *MsgIndexerAssertionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgIndexerAssertionResponse) ProtoMessage()    {}
func (*MsgIndexerAssertionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c48cfcae3522555, []int{1}
}
func (m *MsgIndexerAssertionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIndexerAssertionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIndexerAssertionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIndexerAssertionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIndexerAssertionResponse.Merge(m, src)
}
func (m *MsgIndexerAssertionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIndexerAssertionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIndexerAssertionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIndexerAssertionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgIndexerAssertion)(nil), "shinzonetwork.indexer.v1.MsgIndexerAssertion")
	proto.RegisterType((*MsgIndexerAssertionResponse)(nil), "shinzonetwork.indexer.v1.MsgIndexerAssertionResponse")
}

func init() { proto.RegisterFile("shinzonetwork/indexer/v1/tx.proto", fileDescriptor_8c48cfcae3522555) }

var fileDescriptor_8c48cfcae3522555 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0xfd, 0x11, 0xe0, 0x5a, 0x28, 0xbd, 0x4a, 0x70, 0x0a, 0xc2, 0x4a, 0x3b, 0x40,
	0x88, 0x54, 0x5b, 0x2d, 0x62, 0x61, 0x0b, 0xb0, 0x44, 0x50, 0x09, 0x85, 0x8d, 0xc5, 0xb2, 0x7d,
	0x4f, 0xe7, 0x53, 0xf1, 0x9d, 0x75, 0xef, 0x5c, 0x12, 0x58, 0x10, 0x1b, 0x1b, 0x7f, 0x4a, 0xff,
	0x0c, 0xc6, 0x6e, 0x30, 0xa2, 0x64, 0xe8, 0xbf, 0x81, 0x6c, 0xc7, 0x56, 0x2b, 0xc2, 0xc0, 0x78,
	0x9f, 0xf7, 0x79, 0x4f, 0xcf, 0x5f, 0x3f, 0xba, 0x8f, 0xa9, 0xd2, 0x9f, 0x8c, 0x06, 0xf7, 0xd1,
	0xd8, 0xd3, 0x40, 0x69, 0x01, 0x53, 0xb0, 0xc1, 0xd9, 0x51, 0xe0, 0xa6, 0x7e, 0x6e, 0x8d, 0x33,
	0x8c, 0x5f, 0x53, 0xfc, 0xa5, 0xe2, 0x9f, 0x1d, 0xf5, 0xee, 0x27, 0x06, 0x33, 0x83, 0x41, 0x86,
	0xb2, 0xec, 0xc8, 0x50, 0xd6, 0x2d, 0x07, 0x3f, 0xd7, 0xe8, 0xde, 0x09, 0xca, 0x71, 0xad, 0x8e,
	0x10, 0xc1, 0x3a, 0x65, 0x34, 0xbb, 0x47, 0xbb, 0xa8, 0xa4, 0x06, 0xcb, 0x49, 0x9f, 0x0c, 0x6e,
	0x4d, 0x96, 0x2f, 0x36, 0xa4, 0xbb, 0x89, 0xd1, 0x08, 0x1a, 0x0b, 0x0c, 0xf3, 0x22, 0x0e, 0x4f,
	0x61, 0xc6, 0xd7, 0x2a, 0x65, 0xa7, 0x2d, 0xbc, 0x2d, 0xe2, 0xd7, 0x30, 0x63, 0x4f, 0xe8, 0x5d,
	0x01, 0x1f, 0x40, 0x46, 0x0e, 0xc2, 0x48, 0x08, 0x0b, 0x88, 0x7c, 0xbd, 0x56, 0x1b, 0x3e, 0xaa,
	0x31, 0xdb, 0xa7, 0xdb, 0x68, 0x0a, 0x9b, 0x40, 0x98, 0xa4, 0x91, 0xd2, 0x7c, 0xa3, 0xd2, 0xb6,
	0x6a, 0xf6, 0xb2, 0x44, 0xec, 0x11, 0xdd, 0xb9, 0xaa, 0x84, 0x4a, 0xf0, 0xcd, 0x3e, 0x19, 0x6c,
	0x4c, 0x6e, 0x5f, 0xb1, 0xc6, 0xa2, 0x1c, 0x15, 0x35, 0x9f, 0x51, 0x4a, 0xdd, 0x7a, 0x54, 0xcb,
	0xc6, 0x82, 0x3d, 0xa6, 0xed, 0x02, 0xa1, 0x50, 0x12, 0xd0, 0xf1, 0x1b, 0x7d, 0x32, 0xd8, 0x9e,
	0xdc, 0x69, 0xf0, 0xab, 0x8a, 0xb2, 0x43, 0xca, 0x5a, 0xb1, 0x0c, 0x20, 0x72, 0x85, 0x05, 0x7e,
	0xb3, 0x72, 0x77, 0x9b, 0xca, 0xbb, 0xa6, 0xf0, 0x7c, 0xeb, 0xeb, 0xe5, 0xf9, 0x70, 0x99, 0xd4,
	0xc1, 0x43, 0xfa, 0x60, 0x45, 0xb0, 0x13, 0xc0, 0xbc, 0x8c, 0xe9, 0xf8, 0x1b, 0xa1, 0xeb, 0x27,
	0x28, 0xd9, 0x67, 0xba, 0x37, 0x12, 0xe2, 0xaf, 0xfc, 0x0f, 0xfd, 0x7f, 0xfd, 0x4b, 0x7f, 0xc5,
	0xd4, 0xde, 0xb3, 0xff, 0xd2, 0x9b, 0x25, 0x7a, 0x9b, 0x5f, 0x2e, 0xcf, 0x87, 0xe4, 0xc5, 0x9b,
	0x1f, 0x73, 0x8f, 0x5c, 0xcc, 0x3d, 0xf2, 0x7b, 0xee, 0x91, 0xef, 0x0b, 0xaf, 0x73, 0xb1, 0xf0,
	0x3a, 0xbf, 0x16, 0x5e, 0xe7, 0xfd, 0xb1, 0x54, 0x2e, 0x2d, 0x62, 0x3f, 0x31, 0x59, 0x70, 0xfd,
	0xfe, 0xea, 0x57, 0x5a, 0xc4, 0xc1, 0xb4, 0xbd, 0x45, 0x37, 0xcb, 0x01, 0xe3, 0x6e, 0x75, 0x59,
	0x4f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x81, 0xda, 0xa4, 0xb1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AddIndexerAssertion(ctx context.Context, in *MsgIndexerAssertion, opts ...grpc.CallOption) (*MsgIndexerAssertionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddIndexerAssertion(ctx context.Context, in *MsgIndexerAssertion, opts ...grpc.CallOption) (*MsgIndexerAssertionResponse, error) {
	out := new(MsgIndexerAssertionResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.indexer.v1.Msg/AddIndexerAssertion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AddIndexerAssertion(context.Context, *MsgIndexerAssertion) (*MsgIndexerAssertionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddIndexerAssertion(ctx context.Context, req *MsgIndexerAssertion) (*MsgIndexerAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIndexerAssertion not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddIndexerAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIndexerAssertion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddIndexerAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.indexer.v1.Msg/AddIndexerAssertion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddIndexerAssertion(ctx, req.(*MsgIndexerAssertion))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shinzonetwork.indexer.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddIndexerAssertion",
			Handler:    _Msg_AddIndexerAssertion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shinzonetwork/indexer/v1/tx.proto",
}

func (m *MsgIndexerAssertion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIndexerAssertion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIndexerAssertion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegateSignature) > 0 {
		i -= len(m.DelegateSignature)
		copy(dAtA[i:], m.DelegateSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DelegateSignature)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DelegateDigest) > 0 {
		i -= len(m.DelegateDigest)
		copy(dAtA[i:], m.DelegateDigest)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DelegateDigest)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.AssertionId) > 0 {
		i -= len(m.AssertionId)
		copy(dAtA[i:], m.AssertionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssertionId)))
		i--
		dAtA[i] = 0x32
	}
	if m.SourceChainId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SourceChainId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SourceChain) > 0 {
		i -= len(m.SourceChain)
		copy(dAtA[i:], m.SourceChain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChain)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DelegateAddress) > 0 {
		i -= len(m.DelegateAddress)
		copy(dAtA[i:], m.DelegateAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DelegateAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConsensusPubKey) > 0 {
		i -= len(m.ConsensusPubKey)
		copy(dAtA[i:], m.ConsensusPubKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConsensusPubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIndexerAssertionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIndexerAssertionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIndexerAssertionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgIndexerAssertion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConsensusPubKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DelegateAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SourceChainId != 0 {
		n += 1 + sovTx(uint64(m.SourceChainId))
	}
	l = len(m.AssertionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DelegateDigest)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DelegateSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgIndexerAssertionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgIndexerAssertion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIndexerAssertion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIndexerAssertion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegateAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
			}
			m.SourceChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssertionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssertionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegateDigest = append(m.DelegateDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.DelegateDigest == nil {
				m.DelegateDigest = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegateSignature = append(m.DelegateSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.DelegateSignature == nil {
				m.DelegateSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIndexerAssertionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIndexerAssertionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIndexerAssertionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
