// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shinzonetwork/sourcehub/v1/pending.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RequestKind identifies which caller path produced a pending ICA request.
type RequestKind int32

const (
	RequestKind_REQUEST_KIND_UNSPECIFIED             RequestKind = 0
	RequestKind_REQUEST_KIND_SET_RELATIONSHIP        RequestKind = 1
	RequestKind_REQUEST_KIND_REGISTER_OBJECT         RequestKind = 2
	RequestKind_REQUEST_KIND_REGISTER_SHINZO_OBJECTS RequestKind = 3
	RequestKind_REQUEST_KIND_REQUEST_STREAM_ACCESS   RequestKind = 4
	RequestKind_REQUEST_KIND_REGISTER_SHINZO_POLICY  RequestKind = 5
)

var RequestKind_name = map[int32]string{
	0: "REQUEST_KIND_UNSPECIFIED",
	1: "REQUEST_KIND_SET_RELATIONSHIP",
	2: "REQUEST_KIND_REGISTER_OBJECT",
	3: "REQUEST_KIND_REGISTER_SHINZO_OBJECTS",
	4: "REQUEST_KIND_REQUEST_STREAM_ACCESS",
	5: "REQUEST_KIND_REGISTER_SHINZO_POLICY",
}

var RequestKind_value = map[string]int32{
	"REQUEST_KIND_UNSPECIFIED":             0,
	"REQUEST_KIND_SET_RELATIONSHIP":        1,
	"REQUEST_KIND_REGISTER_OBJECT":         2,
	"REQUEST_KIND_REGISTER_SHINZO_OBJECTS": 3,
	"REQUEST_KIND_REQUEST_STREAM_ACCESS":   4,
	"REQUEST_KIND_REGISTER_SHINZO_POLICY":  5,
}

func (x RequestKind) String() string {
	return proto.EnumName(RequestKind_name, int32(x))
}

func (RequestKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{0}
}

// RequestStatus tracks the lifecycle of a pending ICA request.
type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	RequestStatus_REQUEST_STATUS_PENDING     RequestStatus = 1
	RequestStatus_REQUEST_STATUS_SUCCESS     RequestStatus = 2
	RequestStatus_REQUEST_STATUS_FAILURE     RequestStatus = 3
	RequestStatus_REQUEST_STATUS_TIMEOUT     RequestStatus = 4
)

var RequestStatus_name = map[int32]string{
	0: "REQUEST_STATUS_UNSPECIFIED",
	1: "REQUEST_STATUS_PENDING",
	2: "REQUEST_STATUS_SUCCESS",
	3: "REQUEST_STATUS_FAILURE",
	4: "REQUEST_STATUS_TIMEOUT",
}

var RequestStatus_value = map[string]int32{
	"REQUEST_STATUS_UNSPECIFIED": 0,
	"REQUEST_STATUS_PENDING":     1,
	"REQUEST_STATUS_SUCCESS":     2,
	"REQUEST_STATUS_FAILURE":     3,
	"REQUEST_STATUS_TIMEOUT":     4,
}

func (x RequestStatus) String() string {
	return proto.EnumName(RequestStatus_name, int32(x))
}

func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{1}
}

// PendingICARequest records a single in-flight ICA packet from shinzohub to
// sourcehub and its resolution once the ack or timeout lands.
type PendingICARequest struct {
	Sequence    uint64        `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PortId      string        `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ChannelId   string        `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Kind        RequestKind   `protobuf:"varint,4,opt,name=kind,proto3,enum=shinzonetwork.sourcehub.v1.RequestKind" json:"kind,omitempty"`
	Requestor   string        `protobuf:"bytes,5,opt,name=requestor,proto3" json:"requestor,omitempty"`
	SubmittedAt int64         `protobuf:"varint,6,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	Status      RequestStatus `protobuf:"varint,7,opt,name=status,proto3,enum=shinzonetwork.sourcehub.v1.RequestStatus" json:"status,omitempty"`
	Error       string        `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	ResolvedAt  int64         `protobuf:"varint,9,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	// Kind-specific payload; callers cast to their own proto messages.
	Meta []byte `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	// Raw MsgResponses bytes captured from a successful ack, for callers that
	// want per-message results.
	MsgResponses [][]byte `protobuf:"bytes,11,rep,name=msg_responses,json=msgResponses,proto3" json:"msg_responses,omitempty"`
}

func (m *PendingICARequest) Reset()         { *m = PendingICARequest{} }
func (m *PendingICARequest) String() string { return proto.CompactTextString(m) }
func (*PendingICARequest) ProtoMessage()    {}
func (*PendingICARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{0}
}
func (m *PendingICARequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingICARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingICARequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingICARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingICARequest.Merge(m, src)
}
func (m *PendingICARequest) XXX_Size() int {
	return m.Size()
}
func (m *PendingICARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingICARequest.DiscardUnknown(m)
}

var xxx_messageInfo_PendingICARequest proto.InternalMessageInfo

func (m *PendingICARequest) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PendingICARequest) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *PendingICARequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *PendingICARequest) GetKind() RequestKind {
	if m != nil {
		return m.Kind
	}
	return RequestKind_REQUEST_KIND_UNSPECIFIED
}

func (m *PendingICARequest) GetRequestor() string {
	if m != nil {
		return m.Requestor
	}
	return ""
}

func (m *PendingICARequest) GetSubmittedAt() int64 {
	if m != nil {
		return m.SubmittedAt
	}
	return 0
}

func (m *PendingICARequest) GetStatus() RequestStatus {
	if m != nil {
		return m.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (m *PendingICARequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *PendingICARequest) GetResolvedAt() int64 {
	if m != nil {
		return m.ResolvedAt
	}
	return 0
}

func (m *PendingICARequest) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *PendingICARequest) GetMsgResponses() [][]byte {
	if m != nil {
		return m.MsgResponses
	}
	return nil
}

type SetRelationshipMeta struct {
	Did   string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *SetRelationshipMeta) Reset()         { *m = SetRelationshipMeta{} }
func (m *SetRelationshipMeta) String() string { return proto.CompactTextString(m) }
func (*SetRelationshipMeta) ProtoMessage()    {}
func (*SetRelationshipMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{1}
}
func (m *SetRelationshipMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetRelationshipMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetRelationshipMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetRelationshipMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRelationshipMeta.Merge(m, src)
}
func (m *SetRelationshipMeta) XXX_Size() int {
	return m.Size()
}
func (m *SetRelationshipMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRelationshipMeta.DiscardUnknown(m)
}

var xxx_messageInfo_SetRelationshipMeta proto.InternalMessageInfo

func (m *SetRelationshipMeta) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *SetRelationshipMeta) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type RegisterObjectMeta struct {
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ObjectId     string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (m *RegisterObjectMeta) Reset()         { *m = RegisterObjectMeta{} }
func (m *RegisterObjectMeta) String() string { return proto.CompactTextString(m) }
func (*RegisterObjectMeta) ProtoMessage()    {}
func (*RegisterObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{2}
}
func (m *RegisterObjectMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterObjectMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterObjectMeta.Merge(m, src)
}
func (m *RegisterObjectMeta) XXX_Size() int {
	return m.Size()
}
func (m *RegisterObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterObjectMeta proto.InternalMessageInfo

func (m *RegisterObjectMeta) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *RegisterObjectMeta) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type RegisterShinzoObjectsMeta struct {
	Resources []string `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (m *RegisterShinzoObjectsMeta) Reset()         { *m = RegisterShinzoObjectsMeta{} }
func (m *RegisterShinzoObjectsMeta) String() string { return proto.CompactTextString(m) }
func (*RegisterShinzoObjectsMeta) ProtoMessage()    {}
func (*RegisterShinzoObjectsMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{3}
}
func (m *RegisterShinzoObjectsMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterShinzoObjectsMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterShinzoObjectsMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterShinzoObjectsMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterShinzoObjectsMeta.Merge(m, src)
}
func (m *RegisterShinzoObjectsMeta) XXX_Size() int {
	return m.Size()
}
func (m *RegisterShinzoObjectsMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterShinzoObjectsMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterShinzoObjectsMeta proto.InternalMessageInfo

func (m *RegisterShinzoObjectsMeta) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type RequestStreamAccessMeta struct {
	Did          string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	StreamId     string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ResourceName string `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (m *RequestStreamAccessMeta) Reset()         { *m = RequestStreamAccessMeta{} }
func (m *RequestStreamAccessMeta) String() string { return proto.CompactTextString(m) }
func (*RequestStreamAccessMeta) ProtoMessage()    {}
func (*RequestStreamAccessMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bec399a31016c6b, []int{4}
}
func (m *RequestStreamAccessMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestStreamAccessMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestStreamAccessMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestStreamAccessMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStreamAccessMeta.Merge(m, src)
}
func (m *RequestStreamAccessMeta) XXX_Size() int {
	return m.Size()
}
func (m *RequestStreamAccessMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStreamAccessMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStreamAccessMeta proto.InternalMessageInfo

func (m *RequestStreamAccessMeta) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *RequestStreamAccessMeta) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *RequestStreamAccessMeta) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterEnum("shinzonetwork.sourcehub.v1.RequestKind", RequestKind_name, RequestKind_value)
	proto.RegisterEnum("shinzonetwork.sourcehub.v1.RequestStatus", RequestStatus_name, RequestStatus_value)
	proto.RegisterType((*PendingICARequest)(nil), "shinzonetwork.sourcehub.v1.PendingICARequest")
	proto.RegisterType((*SetRelationshipMeta)(nil), "shinzonetwork.sourcehub.v1.SetRelationshipMeta")
	proto.RegisterType((*RegisterObjectMeta)(nil), "shinzonetwork.sourcehub.v1.RegisterObjectMeta")
	proto.RegisterType((*RegisterShinzoObjectsMeta)(nil), "shinzonetwork.sourcehub.v1.RegisterShinzoObjectsMeta")
	proto.RegisterType((*RequestStreamAccessMeta)(nil), "shinzonetwork.sourcehub.v1.RequestStreamAccessMeta")
}

func init() {
	proto.RegisterFile("shinzonetwork/sourcehub/v1/pending.proto", fileDescriptor_2bec399a31016c6b)
}

var fileDescriptor_2bec399a31016c6b = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x73, 0xdb, 0x44,
	0x14, 0xb6, 0x22, 0xc7, 0x8d, 0x9f, 0x5d, 0x46, 0x2c, 0x1d, 0xaa, 0xba, 0xa9, 0x51, 0x5d, 0x86,
	0x8a, 0x1e, 0xec, 0x29, 0x70, 0x61, 0x18, 0x0e, 0xaa, 0xa3, 0xb6, 0x4b, 0x63, 0xd9, 0xac, 0x64,
	0x66, 0xc8, 0x45, 0x23, 0x5b, 0x8b, 0x2c, 0x62, 0x69, 0x8d, 0x76, 0x1d, 0x08, 0xbf, 0x82, 0x23,
	0x37, 0xfe, 0x0e, 0xc7, 0x1c, 0x39, 0x32, 0xc9, 0x91, 0x3f, 0xc1, 0x68, 0x25, 0x3b, 0xb1, 0xe3,
	0x30, 0xdc, 0xf6, 0x7d, 0xdf, 0xf7, 0xbe, 0xf7, 0x9e, 0xde, 0x6a, 0xc1, 0xe4, 0xb3, 0x38, 0xfd,
	0x95, 0xa5, 0x54, 0xfc, 0xcc, 0xb2, 0xd3, 0x1e, 0x67, 0xcb, 0x6c, 0x4a, 0x67, 0xcb, 0x49, 0xef,
	0xec, 0x65, 0x6f, 0x41, 0xd3, 0x30, 0x4e, 0xa3, 0xee, 0x22, 0x63, 0x82, 0xa1, 0xd6, 0x86, 0xb2,
	0xbb, 0x56, 0x76, 0xcf, 0x5e, 0xb6, 0x1e, 0x44, 0x2c, 0x62, 0x52, 0xd6, 0xcb, 0x4f, 0x45, 0x46,
	0xeb, 0x51, 0xc4, 0x58, 0x34, 0xa7, 0x3d, 0x19, 0x4d, 0x96, 0x3f, 0xf4, 0x82, 0xf4, 0xbc, 0xa0,
	0x3a, 0xbf, 0xab, 0xf0, 0xfe, 0xa8, 0xb0, 0xc7, 0x7d, 0x8b, 0xd0, 0x9f, 0x96, 0x94, 0x0b, 0xd4,
	0x82, 0x03, 0x9e, 0x1f, 0xd3, 0x29, 0xd5, 0x15, 0x43, 0x31, 0xab, 0x64, 0x1d, 0xa3, 0x87, 0x70,
	0x6f, 0xc1, 0x32, 0xe1, 0xc7, 0xa1, 0xbe, 0x67, 0x28, 0x66, 0x9d, 0xd4, 0xf2, 0x10, 0x87, 0xe8,
	0x09, 0xc0, 0x74, 0x16, 0xa4, 0x29, 0x9d, 0xe7, 0x9c, 0x2a, 0xb9, 0x7a, 0x89, 0xe0, 0x10, 0x7d,
	0x05, 0xd5, 0xd3, 0x38, 0x0d, 0xf5, 0xaa, 0xa1, 0x98, 0xef, 0x7d, 0xf6, 0xbc, 0x7b, 0xf7, 0x14,
	0xdd, 0xb2, 0x8d, 0x77, 0x71, 0x1a, 0x12, 0x99, 0x84, 0x0e, 0xa1, 0x9e, 0x15, 0x20, 0xcb, 0xf4,
	0xfd, 0xc2, 0x7a, 0x0d, 0xa0, 0xa7, 0xd0, 0xe4, 0xcb, 0x49, 0x12, 0x0b, 0x41, 0x43, 0x3f, 0x10,
	0x7a, 0xcd, 0x50, 0x4c, 0x95, 0x34, 0xd6, 0x98, 0x25, 0x90, 0x05, 0x35, 0x2e, 0x02, 0xb1, 0xe4,
	0xfa, 0x3d, 0x59, 0xff, 0xd3, 0xff, 0x51, 0xdf, 0x95, 0x09, 0xa4, 0x4c, 0x44, 0x0f, 0x60, 0x9f,
	0x66, 0x19, 0xcb, 0xf4, 0x03, 0x59, 0xbf, 0x08, 0xd0, 0x47, 0xd0, 0xc8, 0x28, 0x67, 0xf3, 0xb3,
	0xa2, 0x74, 0x5d, 0x96, 0x86, 0x15, 0x64, 0x09, 0x84, 0xa0, 0x9a, 0x50, 0x11, 0xe8, 0x60, 0x28,
	0x66, 0x93, 0xc8, 0x33, 0x7a, 0x06, 0xf7, 0x13, 0x1e, 0xf9, 0x19, 0xe5, 0x0b, 0x96, 0x72, 0xca,
	0xf5, 0x86, 0xa1, 0x9a, 0x4d, 0xd2, 0x4c, 0x78, 0x44, 0x56, 0x58, 0xe7, 0x6b, 0xf8, 0xc0, 0xa5,
	0x82, 0xd0, 0x79, 0x20, 0x62, 0x96, 0xf2, 0x59, 0xbc, 0x18, 0xe4, 0xb9, 0x1a, 0xa8, 0x61, 0x1c,
	0xca, 0xb5, 0xd4, 0x49, 0x7e, 0xcc, 0x1b, 0x8b, 0x32, 0xb6, 0x5c, 0x94, 0xfb, 0x28, 0x82, 0xce,
	0x77, 0x80, 0x08, 0x8d, 0x62, 0x2e, 0x68, 0x36, 0x9c, 0xfc, 0x48, 0xa7, 0x62, 0x50, 0x56, 0xce,
	0x7b, 0xcb, 0x87, 0xf5, 0xd3, 0x20, 0xa1, 0xa5, 0x4f, 0x73, 0x05, 0x3a, 0x41, 0x42, 0xd1, 0x63,
	0xa8, 0x33, 0x99, 0x72, 0xbd, 0xe4, 0x83, 0x02, 0xc0, 0x61, 0xe7, 0x4b, 0x78, 0xb4, 0xf2, 0x75,
	0xe5, 0x27, 0x2c, 0xdc, 0xb9, 0xb4, 0x97, 0x7b, 0x2a, 0x9c, 0xb8, 0xae, 0x18, 0x6a, 0xb1, 0xa7,
	0x12, 0xe8, 0x24, 0xf0, 0x70, 0xfd, 0x69, 0x33, 0x1a, 0x24, 0xd6, 0x74, 0x4a, 0x39, 0xbf, 0x63,
	0xaa, 0xc7, 0x50, 0xe7, 0x52, 0x75, 0xa3, 0x89, 0x02, 0xc0, 0xe1, 0xed, 0x31, 0xd4, 0xdb, 0x63,
	0xbc, 0xf8, 0x47, 0x81, 0xc6, 0x8d, 0xab, 0x84, 0x0e, 0x41, 0x27, 0xf6, 0xb7, 0x63, 0xdb, 0xf5,
	0xfc, 0x77, 0xd8, 0x39, 0xf2, 0xc7, 0x8e, 0x3b, 0xb2, 0xfb, 0xf8, 0x35, 0xb6, 0x8f, 0xb4, 0x0a,
	0x7a, 0x0a, 0x4f, 0x36, 0x58, 0xd7, 0xf6, 0x7c, 0x62, 0x1f, 0x5b, 0x1e, 0x1e, 0x3a, 0xee, 0x5b,
	0x3c, 0xd2, 0x14, 0x64, 0xc0, 0xe1, 0x86, 0x84, 0xd8, 0x6f, 0xb0, 0xeb, 0xd9, 0xc4, 0x1f, 0xbe,
	0xfa, 0xc6, 0xee, 0x7b, 0xda, 0x1e, 0x32, 0xe1, 0xe3, 0xdd, 0x0a, 0xf7, 0x2d, 0x76, 0x4e, 0x86,
	0xa5, 0xd0, 0xd5, 0x54, 0xf4, 0x09, 0x74, 0xb6, 0x94, 0x45, 0xe0, 0x7a, 0xc4, 0xb6, 0x06, 0xbe,
	0xd5, 0xef, 0xdb, 0xae, 0xab, 0x55, 0xd1, 0x73, 0x78, 0xf6, 0x9f, 0x8e, 0xa3, 0xe1, 0x31, 0xee,
	0x7f, 0xaf, 0xed, 0xbf, 0xf8, 0x43, 0x81, 0xfb, 0x1b, 0x17, 0x17, 0xb5, 0xa1, 0x75, 0xed, 0x6a,
	0x79, 0x63, 0x77, 0x6b, 0xe2, 0x16, 0x7c, 0xb8, 0xc5, 0x8f, 0x6c, 0xe7, 0x08, 0x3b, 0x6f, 0x34,
	0x65, 0x07, 0xe7, 0x8e, 0x8b, 0x96, 0xf6, 0x76, 0x70, 0xaf, 0x2d, 0x7c, 0x3c, 0x26, 0xb6, 0xa6,
	0xee, 0xe0, 0x3c, 0x3c, 0xb0, 0x87, 0x63, 0x4f, 0xab, 0xbe, 0x72, 0xfe, 0xbc, 0x6c, 0x2b, 0x17,
	0x97, 0x6d, 0xe5, 0xef, 0xcb, 0xb6, 0xf2, 0xdb, 0x55, 0xbb, 0x72, 0x71, 0xd5, 0xae, 0xfc, 0x75,
	0xd5, 0xae, 0x9c, 0x7c, 0x11, 0xc5, 0x22, 0xff, 0xf7, 0xa6, 0x2c, 0xe9, 0x6d, 0xbd, 0x83, 0x32,
	0xca, 0xdf, 0xc1, 0x5f, 0x6e, 0xbc, 0x89, 0xe2, 0x7c, 0x41, 0xf9, 0xa4, 0x26, 0x9f, 0xb0, 0xcf,
	0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x25, 0x6b, 0x9e, 0xdc, 0x3b, 0x05, 0x00, 0x00,
}

func (m *PendingICARequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingICARequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingICARequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MsgResponses) > 0 {
		for iNdEx := len(m.MsgResponses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MsgResponses[iNdEx])
			copy(dAtA[i:], m.MsgResponses[iNdEx])
			i = encodeVarintPending(dAtA, i, uint64(len(m.MsgResponses[iNdEx])))
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.Meta) > 0 {
		i -= len(m.Meta)
		copy(dAtA[i:], m.Meta)
		i = encodeVarintPending(dAtA, i, uint64(len(m.Meta)))
		i--
		dAtA[i] = 0x52
	}
	if m.ResolvedAt != 0 {
		i = encodeVarintPending(dAtA, i, uint64(m.ResolvedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintPending(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x42
	}
	if m.Status != 0 {
		i = encodeVarintPending(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.SubmittedAt != 0 {
		i = encodeVarintPending(dAtA, i, uint64(m.SubmittedAt))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Requestor) > 0 {
		i -= len(m.Requestor)
		copy(dAtA[i:], m.Requestor)
		i = encodeVarintPending(dAtA, i, uint64(len(m.Requestor)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Kind != 0 {
		i = encodeVarintPending(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintPending(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintPending(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Sequence != 0 {
		i = encodeVarintPending(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SetRelationshipMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetRelationshipMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetRelationshipMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Group) > 0 {
		i -= len(m.Group)
		copy(dAtA[i:], m.Group)
		i = encodeVarintPending(dAtA, i, uint64(len(m.Group)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintPending(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterObjectMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterObjectMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterObjectMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ObjectId) > 0 {
		i -= len(m.ObjectId)
		copy(dAtA[i:], m.ObjectId)
		i = encodeVarintPending(dAtA, i, uint64(len(m.ObjectId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ResourceName) > 0 {
		i -= len(m.ResourceName)
		copy(dAtA[i:], m.ResourceName)
		i = encodeVarintPending(dAtA, i, uint64(len(m.ResourceName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterShinzoObjectsMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterShinzoObjectsMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterShinzoObjectsMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Resources) > 0 {
		for iNdEx := len(m.Resources) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Resources[iNdEx])
			copy(dAtA[i:], m.Resources[iNdEx])
			i = encodeVarintPending(dAtA, i, uint64(len(m.Resources[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RequestStreamAccessMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestStreamAccessMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestStreamAccessMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResourceName) > 0 {
		i -= len(m.ResourceName)
		copy(dAtA[i:], m.ResourceName)
		i = encodeVarintPending(dAtA, i, uint64(len(m.ResourceName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StreamId) > 0 {
		i -= len(m.StreamId)
		copy(dAtA[i:], m.StreamId)
		i = encodeVarintPending(dAtA, i, uint64(len(m.StreamId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintPending(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPending(dAtA []byte, offset int, v uint64) int {
	offset -= sovPending(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PendingICARequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovPending(uint64(m.Sequence))
	}
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovPending(uint64(m.Kind))
	}
	l = len(m.Requestor)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	if m.SubmittedAt != 0 {
		n += 1 + sovPending(uint64(m.SubmittedAt))
	}
	if m.Status != 0 {
		n += 1 + sovPending(uint64(m.Status))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	if m.ResolvedAt != 0 {
		n += 1 + sovPending(uint64(m.ResolvedAt))
	}
	l = len(m.Meta)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	if len(m.MsgResponses) > 0 {
		for _, b := range m.MsgResponses {
			l = len(b)
			n += 1 + l + sovPending(uint64(l))
		}
	}
	return n
}

func (m *SetRelationshipMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	l = len(m.Group)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	return n
}

func (m *RegisterObjectMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ResourceName)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	l = len(m.ObjectId)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	return n
}

func (m *RegisterShinzoObjectsMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Resources) > 0 {
		for _, s := range m.Resources {
			l = len(s)
			n += 1 + l + sovPending(uint64(l))
		}
	}
	return n
}

func (m *RequestStreamAccessMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	l = len(m.StreamId)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	l = len(m.ResourceName)
	if l > 0 {
		n += 1 + l + sovPending(uint64(l))
	}
	return n
}

func sovPending(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPending(x uint64) (n int) {
	return sovPending(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PendingICARequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingICARequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingICARequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= RequestKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requestor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requestor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedAt", wireType)
			}
			m.SubmittedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmittedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedAt", wireType)
			}
			m.ResolvedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meta = append(m.Meta[:0], dAtA[iNdEx:postIndex]...)
			if m.Meta == nil {
				m.Meta = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgResponses", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgResponses = append(m.MsgResponses, make([]byte, postIndex-iNdEx))
			copy(m.MsgResponses[len(m.MsgResponses)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetRelationshipMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetRelationshipMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetRelationshipMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Group", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Group = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterObjectMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterObjectMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterObjectMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObjectId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterShinzoObjectsMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterShinzoObjectsMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterShinzoObjectsMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resources = append(m.Resources, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestStreamAccessMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestStreamAccessMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestStreamAccessMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPending(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPending
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPending
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPending
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPending
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPending
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPending
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPending        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPending          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPending = fmt.Errorf("proto: unexpected end of group")
)
