// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shinzonetwork/sourcehub/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Resource int32

const (
	Resource_RESOURCE_PRIMITIVE Resource = 0
	Resource_RESOURCE_VIEW      Resource = 1
)

var Resource_name = map[int32]string{
	0: "RESOURCE_PRIMITIVE",
	1: "RESOURCE_VIEW",
}

var Resource_value = map[string]int32{
	"RESOURCE_PRIMITIVE": 0,
	"RESOURCE_VIEW":      1,
}

func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}

func (Resource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{0}
}

type MsgRegisterSourcehubICA struct {
	Signer                 string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	ControllerConnectionId string `protobuf:"bytes,2,opt,name=controller_connection_id,json=controllerConnectionId,proto3" json:"controller_connection_id,omitempty"`
	HostConnectionId       string `protobuf:"bytes,3,opt,name=host_connection_id,json=hostConnectionId,proto3" json:"host_connection_id,omitempty"`
}

func (m *MsgRegisterSourcehubICA) Reset()         { *m = MsgRegisterSourcehubICA{} }
func (m *MsgRegisterSourcehubICA) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterSourcehubICA) ProtoMessage()    {}
func (*MsgRegisterSourcehubICA) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{0}
}
func (m *MsgRegisterSourcehubICA) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterSourcehubICA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterSourcehubICA.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterSourcehubICA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterSourcehubICA.Merge(m, src)
}
func (m *MsgRegisterSourcehubICA) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterSourcehubICA) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterSourcehubICA.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterSourcehubICA proto.InternalMessageInfo

func (m *MsgRegisterSourcehubICA) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgRegisterSourcehubICA) GetControllerConnectionId() string {
	if m != nil {
		return m.ControllerConnectionId
	}
	return ""
}

func (m *MsgRegisterSourcehubICA) GetHostConnectionId() string {
	if m != nil {
		return m.HostConnectionId
	}
	return ""
}

type MsgRegisterSourcehubICAResponse struct {
}

func (m *MsgRegisterSourcehubICAResponse) Reset()         { *m = MsgRegisterSourcehubICAResponse{} }
func (m *MsgRegisterSourcehubICAResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterSourcehubICAResponse) ProtoMessage()    {}
func (*MsgRegisterSourcehubICAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{1}
}
func (m *MsgRegisterSourcehubICAResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterSourcehubICAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterSourcehubICAResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterSourcehubICAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterSourcehubICAResponse.Merge(m, src)
}
func (m *MsgRegisterSourcehubICAResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterSourcehubICAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterSourcehubICAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterSourcehubICAResponse proto.InternalMessageInfo

type MsgRegisterShinzoPolicy struct {
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgRegisterShinzoPolicy) Reset()         { *m = MsgRegisterShinzoPolicy{} }
func (m *MsgRegisterShinzoPolicy) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterShinzoPolicy) ProtoMessage()    {}
func (*MsgRegisterShinzoPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{2}
}
func (m *MsgRegisterShinzoPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterShinzoPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterShinzoPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterShinzoPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterShinzoPolicy.Merge(m, src)
}
func (m *MsgRegisterShinzoPolicy) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterShinzoPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterShinzoPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterShinzoPolicy proto.InternalMessageInfo

func (m *MsgRegisterShinzoPolicy) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

type MsgRegisterShinzoPolicyResponse struct {
}

func (m *MsgRegisterShinzoPolicyResponse) Reset()         { *m = MsgRegisterShinzoPolicyResponse{} }
func (m *MsgRegisterShinzoPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterShinzoPolicyResponse) ProtoMessage()    {}
func (*MsgRegisterShinzoPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{3}
}
func (m *MsgRegisterShinzoPolicyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterShinzoPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterShinzoPolicyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterShinzoPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterShinzoPolicyResponse.Merge(m, src)
}
func (m *MsgRegisterShinzoPolicyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterShinzoPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterShinzoPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterShinzoPolicyResponse proto.InternalMessageInfo

type MsgRegisterShinzoObjects struct {
	Signer    string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Resources []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (m *MsgRegisterShinzoObjects) Reset()         { *m = MsgRegisterShinzoObjects{} }
func (m *MsgRegisterShinzoObjects) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterShinzoObjects) ProtoMessage()    {}
func (*MsgRegisterShinzoObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{4}
}
func (m *MsgRegisterShinzoObjects) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterShinzoObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterShinzoObjects.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterShinzoObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterShinzoObjects.Merge(m, src)
}
func (m *MsgRegisterShinzoObjects) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterShinzoObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterShinzoObjects.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterShinzoObjects proto.InternalMessageInfo

func (m *MsgRegisterShinzoObjects) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgRegisterShinzoObjects) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type MsgRegisterShinzoObjectsResponse struct {
	Sequence  uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PortId    string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ChannelId string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *MsgRegisterShinzoObjectsResponse) Reset()         { *m = MsgRegisterShinzoObjectsResponse{} }
func (m *MsgRegisterShinzoObjectsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterShinzoObjectsResponse) ProtoMessage()    {}
func (*MsgRegisterShinzoObjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{5}
}
func (m *MsgRegisterShinzoObjectsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterShinzoObjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterShinzoObjectsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterShinzoObjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterShinzoObjectsResponse.Merge(m, src)
}
func (m *MsgRegisterShinzoObjectsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterShinzoObjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterShinzoObjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterShinzoObjectsResponse proto.InternalMessageInfo

func (m *MsgRegisterShinzoObjectsResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MsgRegisterShinzoObjectsResponse) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *MsgRegisterShinzoObjectsResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type MsgRequestStreamAccess struct {
	Signer     string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Resource   Resource `protobuf:"varint,2,opt,name=resource,proto3,enum=shinzonetwork.sourcehub.v1.Resource" json:"resource,omitempty"`
	StreamId   string   `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Did        string   `protobuf:"bytes,4,opt,name=did,proto3" json:"did,omitempty"`
	Expiration uint64   `protobuf:"varint,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (m *MsgRequestStreamAccess) Reset()         { *m = MsgRequestStreamAccess{} }
func (m *MsgRequestStreamAccess) String() string { return proto.CompactTextString(m) }
func (*MsgRequestStreamAccess) ProtoMessage()    {}
func (*MsgRequestStreamAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{6}
}
func (m *MsgRequestStreamAccess) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestStreamAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestStreamAccess.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestStreamAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestStreamAccess.Merge(m, src)
}
func (m *MsgRequestStreamAccess) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestStreamAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestStreamAccess.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestStreamAccess proto.InternalMessageInfo

func (m *MsgRequestStreamAccess) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgRequestStreamAccess) GetResource() Resource {
	if m != nil {
		return m.Resource
	}
	return Resource_RESOURCE_PRIMITIVE
}

func (m *MsgRequestStreamAccess) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *MsgRequestStreamAccess) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *MsgRequestStreamAccess) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type MsgRequestStreamAccessResponse struct {
	Sequence  uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PortId    string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ChannelId string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *MsgRequestStreamAccessResponse) Reset()         { *m = MsgRequestStreamAccessResponse{} }
func (m *MsgRequestStreamAccessResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestStreamAccessResponse) ProtoMessage()    {}
func (*MsgRequestStreamAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{7}
}
func (m *MsgRequestStreamAccessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestStreamAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestStreamAccessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestStreamAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestStreamAccessResponse.Merge(m, src)
}
func (m *MsgRequestStreamAccessResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestStreamAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestStreamAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestStreamAccessResponse proto.InternalMessageInfo

func (m *MsgRequestStreamAccessResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MsgRequestStreamAccessResponse) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *MsgRequestStreamAccessResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

// MsgDeleteStreamAccess revokes a subscriber tuple on sourcehub via the
// shinzohub-controlled ICA channel. Admin-gated; mirrors
// MsgRequestStreamAccess but writes a DeleteRelationship instead of a
// SetRelationship. No expiration field: revocation is immediate.
type MsgDeleteStreamAccess struct {
	Signer   string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Resource Resource `protobuf:"varint,2,opt,name=resource,proto3,enum=shinzonetwork.sourcehub.v1.Resource" json:"resource,omitempty"`
	StreamId string   `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Did      string   `protobuf:"bytes,4,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *MsgDeleteStreamAccess) Reset()         { *m = MsgDeleteStreamAccess{} }
func (m *MsgDeleteStreamAccess) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteStreamAccess) ProtoMessage()    {}
func (*MsgDeleteStreamAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{8}
}
func (m *MsgDeleteStreamAccess) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteStreamAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteStreamAccess.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteStreamAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteStreamAccess.Merge(m, src)
}
func (m *MsgDeleteStreamAccess) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteStreamAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteStreamAccess.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteStreamAccess proto.InternalMessageInfo

func (m *MsgDeleteStreamAccess) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgDeleteStreamAccess) GetResource() Resource {
	if m != nil {
		return m.Resource
	}
	return Resource_RESOURCE_PRIMITIVE
}

func (m *MsgDeleteStreamAccess) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *MsgDeleteStreamAccess) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type MsgDeleteStreamAccessResponse struct {
	Sequence  uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PortId    string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ChannelId string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *MsgDeleteStreamAccessResponse) Reset()         { *m = MsgDeleteStreamAccessResponse{} }
func (m *MsgDeleteStreamAccessResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteStreamAccessResponse) ProtoMessage()    {}
func (*MsgDeleteStreamAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975530337db1a5de, []int{9}
}
func (m *MsgDeleteStreamAccessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteStreamAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteStreamAccessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteStreamAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteStreamAccessResponse.Merge(m, src)
}
func (m *MsgDeleteStreamAccessResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteStreamAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteStreamAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteStreamAccessResponse proto.InternalMessageInfo

func (m *MsgDeleteStreamAccessResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MsgDeleteStreamAccessResponse) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *MsgDeleteStreamAccessResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func init() {
	proto.RegisterEnum("shinzonetwork.sourcehub.v1.Resource", Resource_name, Resource_value)
	proto.RegisterType((*MsgRegisterSourcehubICA)(nil), "shinzonetwork.sourcehub.v1.MsgRegisterSourcehubICA")
	proto.RegisterType((*MsgRegisterSourcehubICAResponse)(nil), "shinzonetwork.sourcehub.v1.MsgRegisterSourcehubICAResponse")
	proto.RegisterType((*MsgRegisterShinzoPolicy)(nil), "shinzonetwork.sourcehub.v1.MsgRegisterShinzoPolicy")
	proto.RegisterType((*MsgRegisterShinzoPolicyResponse)(nil), "shinzonetwork.sourcehub.v1.MsgRegisterShinzoPolicyResponse")
	proto.RegisterType((*MsgRegisterShinzoObjects)(nil), "shinzonetwork.sourcehub.v1.MsgRegisterShinzoObjects")
	proto.RegisterType((*MsgRegisterShinzoObjectsResponse)(nil), "shinzonetwork.sourcehub.v1.MsgRegisterShinzoObjectsResponse")
	proto.RegisterType((*MsgRequestStreamAccess)(nil), "shinzonetwork.sourcehub.v1.MsgRequestStreamAccess")
	proto.RegisterType((*MsgRequestStreamAccessResponse)(nil), "shinzonetwork.sourcehub.v1.MsgRequestStreamAccessResponse")
	proto.RegisterType((*MsgDeleteStreamAccess)(nil), "shinzonetwork.sourcehub.v1.MsgDeleteStreamAccess")
	proto.RegisterType((*MsgDeleteStreamAccessResponse)(nil), "shinzonetwork.sourcehub.v1.MsgDeleteStreamAccessResponse")
}

func init() {
	proto.RegisterFile("shinzonetwork/sourcehub/v1/tx.proto", fileDescriptor_975530337db1a5de)
}

var fileDescriptor_975530337db1a5de = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xce, 0x36, 0x6d, 0x7f, 0xc9, 0xfc, 0x04, 0x0a, 0x0b, 0x4d, 0x2d, 0x43, 0x4d, 0x09, 0x1c,
	0xaa, 0x0a, 0x25, 0xea, 0x1f, 0x24, 0x28, 0x08, 0x51, 0x42, 0x0e, 0x3e, 0x84, 0x56, 0x0e, 0x14,
	0x09, 0x09, 0x45, 0xc9, 0x7a, 0xe5, 0x18, 0x12, 0x6f, 0xea, 0xdd, 0x84, 0x94, 0x13, 0xaa, 0x84,
	0x84, 0xc4, 0x85, 0xa7, 0xe0, 0x86, 0xd4, 0x17, 0xe0, 0xce, 0x09, 0xf5, 0xc8, 0x11, 0x25, 0x87,
	0xbe, 0x06, 0xb2, 0x93, 0x38, 0x76, 0x63, 0xb7, 0x4d, 0xa5, 0x4a, 0xdc, 0x3c, 0xb3, 0xf3, 0xcd,
	0x7c, 0xf3, 0xed, 0x7a, 0x06, 0x6e, 0xf3, 0x9a, 0x69, 0x7d, 0x60, 0x16, 0x15, 0xef, 0x99, 0xfd,
	0x2e, 0xc7, 0x59, 0xcb, 0x26, 0xb4, 0xd6, 0xaa, 0xe6, 0xda, 0x2b, 0x39, 0xd1, 0xc9, 0x36, 0x6d,
	0x26, 0x18, 0x96, 0x03, 0x41, 0x59, 0x2f, 0x28, 0xdb, 0x5e, 0x91, 0xe7, 0x09, 0xe3, 0x0d, 0xc6,
	0x73, 0x0d, 0x6e, 0x38, 0x98, 0x06, 0x37, 0xfa, 0xa0, 0xcc, 0x37, 0x04, 0xf3, 0x45, 0x6e, 0x68,
	0xd4, 0x30, 0xb9, 0xa0, 0x76, 0x69, 0x08, 0x52, 0xf3, 0x9b, 0x38, 0x0d, 0xb3, 0xdc, 0x34, 0x2c,
	0x6a, 0x4b, 0x68, 0x11, 0x2d, 0x25, 0xb5, 0x81, 0x85, 0xef, 0x83, 0x44, 0x98, 0x25, 0x6c, 0x56,
	0xaf, 0x53, 0xbb, 0x4c, 0x98, 0x65, 0x51, 0x22, 0x4c, 0x66, 0x95, 0x4d, 0x5d, 0x9a, 0x72, 0x23,
	0xd3, 0xa3, 0xf3, 0xbc, 0x77, 0xac, 0xea, 0xf8, 0x2e, 0xe0, 0x1a, 0xe3, 0xe2, 0x18, 0x26, 0xee,
	0x62, 0x52, 0xce, 0x89, 0x3f, 0x7a, 0xe3, 0xff, 0xfd, 0xa3, 0x83, 0xe5, 0x41, 0xd1, 0xcc, 0x2d,
	0xb8, 0x19, 0xc1, 0x53, 0xa3, 0xbc, 0xc9, 0x2c, 0x4e, 0x33, 0x8f, 0x83, 0xad, 0xb8, 0x6a, 0x6c,
	0xb3, 0xba, 0x49, 0xf6, 0xa2, 0x5a, 0x39, 0xb1, 0x84, 0x0f, 0xef, 0x95, 0x78, 0x03, 0xd2, 0x58,
	0xc8, 0x56, 0xf5, 0x2d, 0x25, 0x82, 0x47, 0xca, 0x75, 0x03, 0x92, 0x36, 0xed, 0xdf, 0x06, 0x97,
	0xa6, 0x16, 0xe3, 0x4b, 0x49, 0x6d, 0xe4, 0x08, 0x32, 0x68, 0xc3, 0x62, 0x54, 0xfa, 0x21, 0x05,
	0x2c, 0x43, 0x82, 0xd3, 0xdd, 0x16, 0xb5, 0x08, 0x75, 0x0b, 0x4d, 0x6b, 0x9e, 0x8d, 0xe7, 0xe1,
	0xbf, 0x26, 0xb3, 0xc5, 0xe8, 0x22, 0x66, 0x1d, 0x53, 0xd5, 0xf1, 0x02, 0x00, 0xa9, 0x55, 0x2c,
	0x8b, 0xd6, 0x47, 0x82, 0x27, 0x07, 0x1e, 0x55, 0xcf, 0xfc, 0x42, 0x90, 0x76, 0x0b, 0xef, 0xb6,
	0x28, 0x17, 0x25, 0x61, 0xd3, 0x4a, 0x63, 0x93, 0x10, 0xca, 0xa3, 0xbb, 0x7a, 0x02, 0x89, 0x61,
	0x13, 0x6e, 0xad, 0xcb, 0xab, 0x77, 0xb2, 0xd1, 0x0f, 0x30, 0xab, 0x0d, 0x62, 0x35, 0x0f, 0x85,
	0xaf, 0x43, 0x92, 0xbb, 0x95, 0x46, 0x94, 0x12, 0x7d, 0x87, 0xaa, 0xe3, 0x14, 0xc4, 0x75, 0x53,
	0x97, 0xa6, 0x5d, 0xb7, 0xf3, 0x89, 0x15, 0x00, 0xda, 0x69, 0x9a, 0x76, 0xc5, 0x79, 0x1d, 0xd2,
	0x8c, 0xdb, 0xb9, 0xcf, 0x13, 0x14, 0x52, 0x80, 0x12, 0xde, 0xcf, 0x85, 0xca, 0xf8, 0x1d, 0xc1,
	0x5c, 0x91, 0x1b, 0xcf, 0x68, 0x9d, 0x0a, 0xfa, 0x4f, 0xaa, 0x18, 0x54, 0x89, 0xc3, 0x42, 0x28,
	0xdd, 0x8b, 0x14, 0x69, 0xf9, 0x1e, 0x24, 0x86, 0x6d, 0xe0, 0x34, 0x60, 0xad, 0x50, 0xda, 0x7a,
	0xa9, 0xe5, 0x0b, 0xe5, 0x6d, 0x4d, 0x2d, 0xaa, 0x2f, 0xd4, 0x9d, 0x42, 0x2a, 0x86, 0xaf, 0xc0,
	0x25, 0xcf, 0xbf, 0xa3, 0x16, 0x5e, 0xa5, 0xd0, 0xea, 0x8f, 0x19, 0x88, 0x17, 0xb9, 0x81, 0x3f,
	0x23, 0xb8, 0x16, 0x3a, 0xad, 0xd6, 0x4e, 0x12, 0x2e, 0x62, 0x74, 0xc8, 0x0f, 0xcf, 0x01, 0xf2,
	0xd4, 0x09, 0x50, 0xf1, 0x4f, 0x9b, 0x33, 0x53, 0xf1, 0x81, 0xce, 0x4e, 0x25, 0x64, 0x2e, 0xe1,
	0x2f, 0x08, 0xe6, 0xc2, 0xa7, 0xd2, 0xfa, 0x44, 0x69, 0x07, 0x28, 0xf9, 0xd1, 0x79, 0x50, 0x1e,
	0x9b, 0x4f, 0x08, 0xae, 0x86, 0xcd, 0x92, 0xd5, 0x53, 0xb3, 0x8e, 0x61, 0xe4, 0x8d, 0xc9, 0x31,
	0x1e, 0x8f, 0x7d, 0x04, 0x38, 0xe4, 0x67, 0x5c, 0x39, 0x25, 0xe5, 0x38, 0x44, 0x7e, 0x30, 0x31,
	0x64, 0x48, 0x42, 0x9e, 0xf9, 0x78, 0x74, 0xb0, 0x8c, 0x9e, 0x3e, 0xff, 0xd9, 0x55, 0xd0, 0x61,
	0x57, 0x41, 0x7f, 0xba, 0x0a, 0xfa, 0xda, 0x53, 0x62, 0x87, 0x3d, 0x25, 0xf6, 0xbb, 0xa7, 0xc4,
	0x5e, 0xaf, 0x1b, 0xa6, 0x70, 0x32, 0x11, 0xd6, 0xc8, 0x1d, 0xdb, 0xf3, 0xae, 0xe5, 0xec, 0xf9,
	0x8e, 0x6f, 0xe7, 0x8b, 0xbd, 0x26, 0xe5, 0xd5, 0x59, 0x77, 0x7f, 0xaf, 0xfd, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x44, 0x75, 0x6d, 0xb2, 0x1b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterSourcehubICA(ctx context.Context, in *MsgRegisterSourcehubICA, opts ...grpc.CallOption) (*MsgRegisterSourcehubICAResponse, error)
	RegisterShinzoPolicy(ctx context.Context, in *MsgRegisterShinzoPolicy, opts ...grpc.CallOption) (*MsgRegisterShinzoPolicyResponse, error)
	RegisterShinzoObjects(ctx context.Context, in *MsgRegisterShinzoObjects, opts ...grpc.CallOption) (*MsgRegisterShinzoObjectsResponse, error)
	RequestStreamAccess(ctx context.Context, in *MsgRequestStreamAccess, opts ...grpc.CallOption) (*MsgRequestStreamAccessResponse, error)
	DeleteStreamAccess(ctx context.Context, in *MsgDeleteStreamAccess, opts ...grpc.CallOption) (*MsgDeleteStreamAccessResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterSourcehubICA(ctx context.Context, in *MsgRegisterSourcehubICA, opts ...grpc.CallOption) (*MsgRegisterSourcehubICAResponse, error) {
	out := new(MsgRegisterSourcehubICAResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.sourcehub.v1.Msg/RegisterSourcehubICA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterShinzoPolicy(ctx context.Context, in *MsgRegisterShinzoPolicy, opts ...grpc.CallOption) (*MsgRegisterShinzoPolicyResponse, error) {
	out := new(MsgRegisterShinzoPolicyResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.sourcehub.v1.Msg/RegisterShinzoPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterShinzoObjects(ctx context.Context, in *MsgRegisterShinzoObjects, opts ...grpc.CallOption) (*MsgRegisterShinzoObjectsResponse, error) {
	out := new(MsgRegisterShinzoObjectsResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.sourcehub.v1.Msg/RegisterShinzoObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestStreamAccess(ctx context.Context, in *MsgRequestStreamAccess, opts ...grpc.CallOption) (*MsgRequestStreamAccessResponse, error) {
	out := new(MsgRequestStreamAccessResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.sourcehub.v1.Msg/RequestStreamAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteStreamAccess(ctx context.Context, in *MsgDeleteStreamAccess, opts ...grpc.CallOption) (*MsgDeleteStreamAccessResponse, error) {
	out := new(MsgDeleteStreamAccessResponse)
	err := c.cc.Invoke(ctx, "/shinzonetwork.sourcehub.v1.Msg/DeleteStreamAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterSourcehubICA(context.Context, *MsgRegisterSourcehubICA) (*MsgRegisterSourcehubICAResponse, error)
	RegisterShinzoPolicy(context.Context, *MsgRegisterShinzoPolicy) (*MsgRegisterShinzoPolicyResponse, error)
	RegisterShinzoObjects(context.Context, *MsgRegisterShinzoObjects) (*MsgRegisterShinzoObjectsResponse, error)
	RequestStreamAccess(context.Context, *MsgRequestStreamAccess) (*MsgRequestStreamAccessResponse, error)
	DeleteStreamAccess(context.Context, *MsgDeleteStreamAccess) (*MsgDeleteStreamAccessResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterSourcehubICA(ctx context.Context, req *MsgRegisterSourcehubICA) (*MsgRegisterSourcehubICAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSourcehubICA not implemented")
}
func (*UnimplementedMsgServer) RegisterShinzoPolicy(ctx context.Context, req *MsgRegisterShinzoPolicy) (*MsgRegisterShinzoPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterShinzoPolicy not implemented")
}
func (*UnimplementedMsgServer) RegisterShinzoObjects(ctx context.Context, req *MsgRegisterShinzoObjects) (*MsgRegisterShinzoObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterShinzoObjects not implemented")
}
func (*UnimplementedMsgServer) RequestStreamAccess(ctx context.Context, req *MsgRequestStreamAccess) (*MsgRequestStreamAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestStreamAccess not implemented")
}
func (*UnimplementedMsgServer) DeleteStreamAccess(ctx context.Context, req *MsgDeleteStreamAccess) (*MsgDeleteStreamAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStreamAccess not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterSourcehubICA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterSourcehubICA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterSourcehubICA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.sourcehub.v1.Msg/RegisterSourcehubICA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterSourcehubICA(ctx, req.(*MsgRegisterSourcehubICA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterShinzoPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterShinzoPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterShinzoPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.sourcehub.v1.Msg/RegisterShinzoPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterShinzoPolicy(ctx, req.(*MsgRegisterShinzoPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterShinzoObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterShinzoObjects)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterShinzoObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.sourcehub.v1.Msg/RegisterShinzoObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterShinzoObjects(ctx, req.(*MsgRegisterShinzoObjects))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestStreamAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestStreamAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestStreamAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.sourcehub.v1.Msg/RequestStreamAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestStreamAccess(ctx, req.(*MsgRequestStreamAccess))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteStreamAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteStreamAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteStreamAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinzonetwork.sourcehub.v1.Msg/DeleteStreamAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteStreamAccess(ctx, req.(*MsgDeleteStreamAccess))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shinzonetwork.sourcehub.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSourcehubICA",
			Handler:    _Msg_RegisterSourcehubICA_Handler,
		},
		{
			MethodName: "RegisterShinzoPolicy",
			Handler:    _Msg_RegisterShinzoPolicy_Handler,
		},
		{
			MethodName: "RegisterShinzoObjects",
			Handler:    _Msg_RegisterShinzoObjects_Handler,
		},
		{
			MethodName: "RequestStreamAccess",
			Handler:    _Msg_RequestStreamAccess_Handler,
		},
		{
			MethodName: "DeleteStreamAccess",
			Handler:    _Msg_DeleteStreamAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shinzonetwork/sourcehub/v1/tx.proto",
}

func (m *MsgRegisterSourcehubICA) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterSourcehubICA) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterSourcehubICA) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HostConnectionId) > 0 {
		i -= len(m.HostConnectionId)
		copy(dAtA[i:], m.HostConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.HostConnectionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ControllerConnectionId) > 0 {
		i -= len(m.ControllerConnectionId)
		copy(dAtA[i:], m.ControllerConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ControllerConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterSourcehubICAResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterSourcehubICAResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterSourcehubICAResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterShinzoPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterShinzoPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterShinzoPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterShinzoPolicyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterShinzoPolicyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterShinzoPolicyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterShinzoObjects) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterShinzoObjects) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterShinzoObjects) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Resources) > 0 {
		for iNdEx := len(m.Resources) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Resources[iNdEx])
			copy(dAtA[i:], m.Resources[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Resources[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterShinzoObjectsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterShinzoObjectsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterShinzoObjectsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestStreamAccess) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestStreamAccess) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestStreamAccess) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Expiration))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StreamId) > 0 {
		i -= len(m.StreamId)
		copy(dAtA[i:], m.StreamId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StreamId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Resource != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Resource))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestStreamAccessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestStreamAccessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestStreamAccessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteStreamAccess) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteStreamAccess) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteStreamAccess) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StreamId) > 0 {
		i -= len(m.StreamId)
		copy(dAtA[i:], m.StreamId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StreamId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Resource != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Resource))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteStreamAccessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteStreamAccessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteStreamAccessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterSourcehubICA) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ControllerConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.HostConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterSourcehubICAResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterShinzoPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterShinzoPolicyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterShinzoObjects) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Resources) > 0 {
		for _, s := range m.Resources {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRegisterShinzoObjectsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRequestStreamAccess) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Resource != 0 {
		n += 1 + sovTx(uint64(m.Resource))
	}
	l = len(m.StreamId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Expiration != 0 {
		n += 1 + sovTx(uint64(m.Expiration))
	}
	return n
}

func (m *MsgRequestStreamAccessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteStreamAccess) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Resource != 0 {
		n += 1 + sovTx(uint64(m.Resource))
	}
	l = len(m.StreamId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteStreamAccessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterSourcehubICA) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterSourcehubICA: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterSourcehubICA: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControllerConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterSourcehubICAResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterSourcehubICAResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterSourcehubICAResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterShinzoPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterShinzoPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterShinzoPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterShinzoPolicyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterShinzoPolicyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterShinzoPolicyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterShinzoObjects) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterShinzoObjects: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterShinzoObjects: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resources = append(m.Resources, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterShinzoObjectsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterShinzoObjectsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterShinzoObjectsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestStreamAccess) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestStreamAccess: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestStreamAccess: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			m.Resource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Resource |= Resource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestStreamAccessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestStreamAccessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestStreamAccessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteStreamAccess) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteStreamAccess: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteStreamAccess: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			m.Resource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Resource |= Resource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteStreamAccessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteStreamAccessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteStreamAccessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
