[global]
log_level = 'info'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true
[mode.connections]
enabled = true
[mode.channels]
enabled = true
[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[[chains]]
id = 'sourcehub'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:27686'
grpc_addr = 'http://127.0.0.1:9095'
event_source = { mode = 'push', url = 'ws://127.0.0.1:27686/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'source'
key_name = 'source'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 4000000
gas_price = { price = 0.025, denom = 'uopen' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '14days'
trust_threshold = '2/3'
address_type = { derivation = 'cosmos' }

[[chains]]
id = '9001'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
event_source = { mode = 'push', url = 'ws://127.0.0.1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'shinzo'
key_name = 'shinzo'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 4000000
gas_price = { price = 0.00001, denom = 'ushinzo' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '14days'
trust_threshold = '2/3'
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/cosmos.evm.crypto.v1.ethsecp256k1.PubKey' } }