name: ICT E2E

on:
  pull_request:

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: 1.24.6
  TAR_PATH: /tmp/docker-image.tar
  IMAGE_NAME: docker-image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false  # we use cache/restore

      # Cache go mod cache for interchaintest module
      - name: Go Mod Cache - Interchaintest
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-ict-${{ hashFiles('interchaintest/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-ict-

      - name: Download Go Dependencies
        run: |
          go mod download
          cd interchaintest && go mod download

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: bankd:local
          outputs: type=docker,dest=${{ env.TAR_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.TAR_PATH }}
