name: Unit tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-unit-tests
  cancel-in-progress: true

env:
  GO_VERSION: 1.24.6
  CGO_ENABLED: "1"
  GOPRIVATE: "github.com/shinzonetwork"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum

      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum

      - name: Fetch dependencies
        run: go mod tidy

      - uses: extractions/setup-just@v3
      - name: Run unit tests
        if: env.GIT_DIFF
        run: just test-unit test-coverage
